project:
  type: website
  output-dir: docs
  render:
    - "notes.qmd"
    - "tutorial.qmd"
    - embbeded_slides.qmd
    - slides/slides.qmd
website:
  title: 'Data Analysis Week 1'
  favicon: UofG_Coat_of_Arms.png
  navbar:
    logo: UofG.png
    left:
    - href: notes.qmd
      text: Notes
    - href: tutorial.qmd
      text: Extra material
    - href: embbeded_slides.qmd
      text: Slides
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
