project:
  type: website
  output-dir: docs
render:
    - "notes_24_25.qmd"
    - "about.qmd"
website:
  title: "Week 3: Regression modelling part 2"
  favicon: UofG_Coat_of_Arms.png
  navbar:
    logo: UofG.png
    left:
    - href: notes_24_25.qmd
      text: Notes
    - href: about.qmd
      text: Week Tasks
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual

