project:
  type: website
  output-dir: docs
  render:
    - "notes.qmd"
    - "extra_material.qmd"
    - "Example_report.html"
website:
  title: 'Data Analysis Week 2'
  favicon: UofG_Coat_of_Arms.png
  navbar:
    logo: UofG.png
    left:
    - href: notes.qmd
      text: Notes
    - href: extra_material.qmd
      text: Presentations with Quarto
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
