project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - embbeded_slides.qmd
  - slides/slides.qmd
website:
  title: Data Analysis Week 9
  favicon: UofG_Coat_of_Arms.png
  navbar:
    logo: UofG.png
    left:
    - href: index.qmd
      text: Notes
    - href: embbeded_slides.qmd
      text: Slides
format:
  html:
    embed-resources: true
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
