---
title: "Week 1 Tasks"
format: 
  html: default
  pdf: default
editor: visual
---

# Tasks

1.  From the `flights` data set, subset the data for the airline carrier `JetBlue Airways` and produce a scatterplot of their departure delays against arrival delays using `ggplot`. Interpret the scatterplot.

<!-- -->

2.  Produce a histogram of the hourly temperature from Newark Liberty International (EWR) Airport in 2013 using `ggplot`. How does the temperature distribution compare with that from all airports in New York City in 2013?

<!-- -->

3.  For John F. Kennedy Airport, produce boxplots (using a single `ggplot` command) of the hourly temperature for the months May, June, July, August and September. How does the hourly temperature change during this period?

<!-- -->

4.  Take a look at the `mtcars` data set within the `datasets` library relating to data extracted from the 1974 *Motor Trend* US magazine. Using `ggplot`, produce a faceted barplot of the categorical variables relating to the number of cylinders (`cyl`) and the automobiles transmission (`am`). Interpret the barplot.

<!-- -->

5.  Produce a linegraph of the hourly temperature at LAGuardia (LGA) Airport for the month of October 2013. Interpret the linegraph.
