---
title: "Week 2 Tasks"
format: 
  html: default
  pdf:  default
editor: visual
---

# Tasks

1.  Examine the relationship between teaching score and age in the `evals` data set. What is the value of the correlation coefficient? How would you interpret this verbally? Finally, produce a scatterplot of teaching score and age.

<!-- ```{r task2-solution, exercise=TRUE, exercise.eval=FALSE,  exercise.lines = 10, exercise.cap = "Task 2", exercise.timelimit=30} -->

<!-- evals.age <- evals %>% -->

<!--   select(score, age) -->

<!-- evals.age %>% -->

<!--   get_correlation(formula = score ~ age) -->

<!-- ggplot(evals.age, aes(x = age, y = score)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Age", y = "Teaching Score", title = "Relationship between Teaching Score and Age") -->

<!-- ``` -->

2.  Perform a formal analysis of the relationship between teaching score and age by fitting a simple linear regression model. Superimpose your best-fitting line onto your scatterplot from Task 2.

<!-- ```{r task3-solution, exercise=TRUE, exercise.eval=FALSE, exercise.lines = 6, exercise.cap = "Task 3", exercise.timelimit=30} -->

<!-- evals.age <- evals %>% -->

<!--   select(score, age) -->

<!-- model <- lm(score ~ age, data = evals.age) -->

<!-- model -->

<!-- ggplot(evals.age, aes(x = age, y = score)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Age", y = "Teaching Score", title = "Relationship between Teaching Score and Age") + -->

<!--   geom_smooth(method = "lm", se = FALSE) -->

<!-- regression.points <- get_regression_points(model) -->

<!-- regression.points -->

<!-- ``` -->

3.  Assess the model assumptions from Task 2 by plotting the residuals against the explanatory variable and fitted values, respectively. Also, plot a histogram of the residuals to assess whether they are normally distributed.

<!-- ```{r task4-solution, exercise=TRUE, exercise.eval=FALSE, exercise.lines = 12, exercise.cap = "Task 4", exercise.timelimit=30} -->

<!-- evals.age <- evals %>% -->

<!--   select(score, age) -->

<!-- model <- lm(score ~ age, data = evals.age) -->

<!-- regression.points <- get_regression_points(model) -->

<!-- ggplot(regression.points, aes(x = age, y = residual)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Age", y = "Residual") + -->

<!--   geom_hline(yintercept = 0, col = "blue", size = 1) -->

<!-- ggplot(regression.points, aes(x = score_hat, y = residual)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Fitted values", y = "Residual") + -->

<!--   geom_hline(yintercept = 0, col = "blue", size = 1) -->

<!-- ggplot(regression.points, aes(x = residual)) + -->

<!--   geom_histogram(binwidth = 0.25, color = "white") + -->

<!--   labs(x = "Residual") -->

<!-- ``` -->

4.  Perform the same analysis we did on life expectancy from the `gapminder` data set in 2007. However, subset the data for the year 1997. Are there any differences in the results across this 10 year period?

    <!-- ```{r task5-solution, exercise=TRUE, exercise.eval=FALSE,  exercise.lines = 12, exercise.cap = "Task 5", exercise.timelimit=30} -->

    <!-- gapminder1997 <- gapminder %>% -->

    <!--   filter(year == 1997) %>% -->

    <!--   select(country, continent, lifeExp) -->

    <!-- lifeExp.continent <- gapminder1997 %>% -->

    <!--   group_by(continent) %>% -->

    <!--   summarize(median = median(lifeExp), mean = mean(lifeExp)) -->

    <!-- lifeExp.continent -->

    <!-- lifeExp.model <- lm(lifeExp ~ continent, data = gapminder1997) -->

    <!-- lifeExp.model -->

    <!-- ``` -->

5.  Return to the `Credit` data set and fit a multiple regression model with `Balance` as the outcome variable, and `Income` and `Age` as the explanatory variables, respectively. Assess the assumptions of the multiple regression model.

<!-- ```{r task2-solution, echo = TRUE, eval = TRUE} -->

<!-- Cred <- Credit %>% -->

<!--   select(Balance, Income, Age) -->

<!--  -->

<!-- Cred %>% -->

<!--   skim() -->

<!--  -->

<!-- Cred %>% -->

<!--   cor() -->

<!--  -->

<!-- ggplot(Cred, aes(x = Age, y = Balance)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Age (in years)", y = "Credit card balance (in $)",  -->

<!--        title = "Relationship between balance and age") + -->

<!--   geom_smooth(method = "lm", se = FALSE) -->

<!--  -->

<!-- plot_ly(Cred, x = ~Income, y = ~Age, z = ~Balance, -->

<!--         type = "scatter3d", mode = "markers") -->

<!--  -->

<!-- Balance.model <- lm(Balance ~ Age + Income, data = Cred) -->

<!-- get_regression_table(Balance.model) -->

<!--  -->

<!-- regression.points <- get_regression_points(Balance.model) -->

<!--  -->

<!-- ggplot(regression.points, aes(x = Income, y = residual)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Income (in $1000)", y = "Residual", title = "Residuals vs income")  + -->

<!--   geom_hline(yintercept = 0, col = "blue", size = 1) -->

<!--  -->

<!-- ggplot(regression.points, aes(x = Age, y = residual)) + -->

<!--   geom_point() + -->

<!--   labs(x = "Age (in years)", y = "Residual", title = "Residuals vs age")  + -->

<!--   geom_hline(yintercept = 0, col = "blue", size = 1) -->

<!--  -->

<!-- ggplot(regression.points, aes(x = residual)) + -->

<!--   geom_histogram(color = "white") + -->

<!--   labs(x = "Residual") -->

<!-- ``` -->
