<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Week 2: Regression modelling part 1 – Data Analysis Week 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./UofG_Coat_of_Arms.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/bootstrap-icons-1.9.1/all.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="include/webex.css">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./UofG.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analysis Week 2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Week 2 Tasks</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression"><span class="header-section-number">2</span> Simple linear regression</a></li>
  <li>
<a href="#simple-linear-regression-with-one-numerical-explanatory-variable" id="toc-simple-linear-regression-with-one-numerical-explanatory-variable" class="nav-link" data-scroll-target="#simple-linear-regression-with-one-numerical-explanatory-variable"><span class="header-section-number">3</span> Simple linear regression with one numerical explanatory variable</a>
  <ul class="collapse">
<li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">3.1</span> Exploratory data analysis</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">3.2</span> Correlation</a></li>
  <li><a href="#formal-analysis" id="toc-formal-analysis" class="nav-link" data-scroll-target="#formal-analysis"><span class="header-section-number">3.3</span> Formal analysis</a></li>
  <li><a href="#assessing-model-fit" id="toc-assessing-model-fit" class="nav-link" data-scroll-target="#assessing-model-fit"><span class="header-section-number">3.4</span> Assessing model fit</a></li>
  </ul>
</li>
  <li>
<a href="#simple-linear-regression-with-one-categorical-explanatory-variable" id="toc-simple-linear-regression-with-one-categorical-explanatory-variable" class="nav-link" data-scroll-target="#simple-linear-regression-with-one-categorical-explanatory-variable"><span class="header-section-number">4</span> Simple linear regression with one categorical explanatory variable</a>
  <ul class="collapse">
<li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1"><span class="header-section-number">4.1</span> Exploratory data analysis</a></li>
  <li><a href="#formal-analysis-1" id="toc-formal-analysis-1" class="nav-link" data-scroll-target="#formal-analysis-1"><span class="header-section-number">4.2</span> Formal analysis</a></li>
  <li><a href="#assessing-model-fit-1" id="toc-assessing-model-fit-1" class="nav-link" data-scroll-target="#assessing-model-fit-1"><span class="header-section-number">4.3</span> Assessing model fit</a></li>
  </ul>
</li>
  <li>
<a href="#multiple-regression-with-two-numerical-explanatory-variables" id="toc-multiple-regression-with-two-numerical-explanatory-variables" class="nav-link" data-scroll-target="#multiple-regression-with-two-numerical-explanatory-variables"><span class="header-section-number">5</span> Multiple regression with two numerical explanatory variables</a>
  <ul class="collapse">
<li><a href="#exploratory-data-analysis-2" id="toc-exploratory-data-analysis-2" class="nav-link" data-scroll-target="#exploratory-data-analysis-2"><span class="header-section-number">5.1</span> Exploratory data analysis</a></li>
  <li><a href="#formal-analysis-2" id="toc-formal-analysis-2" class="nav-link" data-scroll-target="#formal-analysis-2"><span class="header-section-number">5.2</span> Formal analysis</a></li>
  <li><a href="#assessing-model-fit-for-multiple-regression" id="toc-assessing-model-fit-for-multiple-regression" class="nav-link" data-scroll-target="#assessing-model-fit-for-multiple-regression"><span class="header-section-number">5.3</span> Assessing model fit for multiple regression</a></li>
  </ul>
</li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Week 2: Regression modelling part 1</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>Now that we are comfortable with visualising and manipulating data in R, we can now proceed onto modelling data. The key idea behind modelling data is to infer the relationship between an:</p>
<ul>
<li>
<strong>outcome (or response) variable</strong> <span class="math inline">\(y\)</span> and</li>
<li>an <strong>explanatory (or predictor) variable</strong> <span class="math inline">\(x\)</span>, which can also be referred to as an <strong>independent variable</strong> or <strong>covariate</strong>.</li>
</ul>
<p>Modelling can be used for two purposes:</p>
<ol type="1">
<li><p><strong>Explanation</strong>: For describing the relationship between an outcome variable <span class="math inline">\(y\)</span> and an explanatory variable <em>x</em>, and determining the potential significance of such relationships using quantifiable measures.</p></li>
<li><p><strong>Prediction</strong>: for predicting the outcome variable <span class="math inline">\(y\)</span> given information from one or more explanatory variables.</p></li>
</ol>
<p>There are many different modelling techniques. However, we will begin with one of the easier to understand and commonly-used approaches, <strong>linear regression</strong>. In particular, we will start by looking at <strong>simple linear regression</strong>, where we only have one explanatory variable.</p>
<p><strong>Note</strong>: Additional information and examples can be found in <a href="https://moderndive.com/6-regression.html">Chapter 6</a> of <a href="https://moderndive.com/index.html">An Introduction to Statistical and Data Science via R</a>.</p>
</section><section id="simple-linear-regression" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Simple linear regression</h1>
<p>For a response variable <span class="math inline">\(y\)</span> and an explanatory variable <span class="math inline">\(x\)</span>, the data can be expressed as:</p>
<p><span class="math display">\[(y_i, x_i), ~~~~ i = 1,\ldots,n.\]</span> That is, we have <span class="math inline">\(n\)</span> observations of <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>. A statistical model is a mathematical statement describing the variability in a random variable <span class="math inline">\(y\)</span>, which includes any relationship with the explanatory variable <span class="math inline">\(x\)</span>. The inclusion of random (unpredictable) components <span class="math inline">\(\epsilon\)</span>, makes the model statistical, rather than deterministic. A simple linear regression model involves, as the name suggests, fitting a linear regression line to the data. Hence, a simple linear regression model can be written as follows:</p>
<p><span class="math display">\[y_i = \alpha + \beta x_i + \epsilon_i, ~~~~ \epsilon_i \sim N(0, \sigma^2),\]</span> where</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span> is the <span class="math inline">\(i^{th}\)</span> observation of the response variable;</li>
<li>
<span class="math inline">\(\alpha\)</span> is the <strong>intercept</strong> of the regression line;</li>
<li>
<span class="math inline">\(\beta\)</span> is the <strong>slope</strong> of the regression line;</li>
<li>
<span class="math inline">\(x_i\)</span> is the <span class="math inline">\(i^{th}\)</span> observation of the explanatory variable; and</li>
<li>
<span class="math inline">\(\epsilon_i\)</span> is the <span class="math inline">\(i^{th}\)</span> random component.</li>
</ul>
<p>The random components, <span class="math inline">\(\epsilon_i\)</span>, are normally distributed with mean zero and constant variance <span class="math inline">\(\sigma^2\)</span>, such that we are essentially adding random white noise to the deterministic part of the model (<span class="math inline">\(\alpha + \beta x_i\)</span>). Thus, the full probability model for <span class="math inline">\(y_i\)</span> given <span class="math inline">\(x_i\)</span> (<span class="math inline">\(y_i | x_i\)</span>) can be written as</p>
<p><span class="math display">\[y_i | x_i \sim N(\alpha + \beta x_i, \sigma^2).\]</span></p>
<p>Hence, the mean comes from the deterministic part of the model, while the variance comes from the random part. We shall now look into fitting a simple linear regression model to some data.</p>
</section><section id="simple-linear-regression-with-one-numerical-explanatory-variable" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Simple linear regression with one numerical explanatory variable</h1>
<p>First, we need to load the following packages into R:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://moderndive.github.io/moderndive/">moderndive</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/jennybc/gapminder">gapminder</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Student feedback in higher education is extremely important when it comes to the evaluation of teaching techniques, materials, and improvements in teaching methods and technologies. However, there have been studies into potential bias factors when feedback is provided, such as the physical appearance of the teacher; see <a href="https://www.journals.elsevier.com/economics-of-education-review/">Economics of Education Review</a> for details. Here, we shall look at a study from student evaluations of <span class="math inline">\(n=463\)</span> professors from The University of Texas at Austin. In particular, we will examine the evaluation scores of the instructors based purely on one numerical variable: their <em>beauty score</em>. Therefore, our simple linear regression model will consist of:</p>
<ul>
<li>the numerical outcome variable <em>teaching score</em> (<span class="math inline">\(y\)</span>); and</li>
<li>the numerical explanatory variable <em>beauty score</em> (<span class="math inline">\(x\)</span>).</li>
</ul>
<section id="exploratory-data-analysis" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">3.1</span> Exploratory data analysis</h2>
<p>Before you ever do any statistical modelling of data, you should always perform an <strong>exploratory data analysis</strong> of the data. Performing an exploratory data analysis can give us an idea of the distribution of the data, and whether it contains any strange values, such as <strong>outliers</strong> or <strong>missing values</strong>. However, more importantly, it is used to inform which statistical model we should fit to the data. An exploratory data analysis may involve:</p>
<ol type="1">
<li>Looking at the raw values of the data, either by looking at the spreadsheet directly, or using R.</li>
<li>By computing various summary statistics, such as the <em>five-number summary</em>, means, and standard deviations.</li>
<li>Plotting the data using various data visualisation techniques.</li>
</ol>
<p>Let’s examine the data <code>evals</code>. We can look at the raw values from <code>evals</code> using the RStudio pop-up spreadsheet viewer using:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">evals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>At the moment we are only really interested in the instructors teaching (<code>score</code>) and beauty (<code>bty_avg</code>) scores, and so we can look at a subset of the data as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">evals.scores</span> <span class="op">&lt;-</span> <span class="va">evals</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">score</span>, <span class="va">bty_avg</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The outcome variable <code>score</code> is a numerical average of the average teaching score based on students’ evaluations between 1 and 5. The explanatory variable <code>bty_avg</code> is the numerical variable of the average <em>beauty</em> score from a panel of six students’ scores between 1 and 10. As both variables are numerical, we can compute summary statistics for them using the <code>skim</code> function from the <code>skimr</code> package as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">evals.scores</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">evals.scores</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">463</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">4.30</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▅▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">8.17</td>
<td style="text-align: left;">▃▇▇▃▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This provides us with the following information:</p>
<ul>
<li>
<code>missing</code>: the number of missing values.</li>
<li>
<code>complete</code>: the number of non-missing values.</li>
<li>
<code>n</code>: the total number of observations.</li>
<li>
<code>mean</code>: the mean or average.</li>
<li>
<code>sd</code>: the standard deviation.</li>
<li>
<code>p0</code>: the <span class="math inline">\(0^{th}\)</span> percentile: the value at which 0% of values are smaller than it (i.e.&nbsp;the <em>minimum</em>).</li>
<li>
<code>p25</code>: the <span class="math inline">\(25^{th}\)</span> percentile: the value at which 25% of values are smaller than it (i.e.&nbsp;the <em>1st quartile</em>).</li>
<li>
<code>p50</code>: the <span class="math inline">\(50^{th}\)</span> percentile: the value at which 50% of values are smaller than it (i.e.&nbsp;the <em>median</em>).</li>
<li>
<code>p75</code>: the <span class="math inline">\(75^{th}\)</span> percentile: the value at which 75% of values are smaller than it (i.e.&nbsp;the <em>3rd quartile</em>).</li>
<li>
<code>p100</code>: the <span class="math inline">\(100^{th}\)</span> percentile: the value at which 100% of values are smaller than it (i.e.&nbsp;the <em>maximum</em>).</li>
<li>
<code>hist</code>: provides a snapshot of a histogram of the variable.</li>
</ul>
<p>These summary statistics give us an idea of how both variables are distributed. For example, the mean teaching score (<code>score</code>) is 4.17 out 5, while the mean beauty score (<code>bty_avg</code>) is 4.42 out of 10. Also, the middle 50% of the data for <code>score</code> lies between 3.8 and 4.6, while the middle 50% of <code>bty_avg</code> lies between 3.17 and 5.5.</p>
</section><section id="correlation" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="correlation">
<span class="header-section-number">3.2</span> Correlation</h2>
<p>The above summary statistics provide information about each variable separately. However, we are interested in a potential relationship between the two variables and as such it would be of interest to evaluate some statistic that considers both variables simultaneously. One such statistic is the <strong>correlation</strong>, which ranges between -1 and 1 and describes the strength of the linear relationship between two numerical variables, such that</p>
<ul>
<li>-1 indicates a perfect <em>negative relationship</em>. That is, as the values of one variable increase, the values of the other decrease.</li>
<li>0 indicates no relationship. The values of both variables increase/decrease independently of one another.</li>
<li>1 indicates a perfect <em>positive relationship</em>. That is, the values of both variables increase simultaneously.</li>
</ul>
<p>The correlation coefficient <span class="math inline">\(\rho(\cdot)\)</span> between two variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> can be computed as:</p>
<p><span class="math display">\[
\rho (x,y) = \dfrac{\sum_{i=1}^n (x_i -\bar{x})(y_i-\bar{y})}{\sqrt{\sum_{i=1}^n (x_i-\bar{x})^2}\sqrt{\sum_{i=1}^n (y_i-\bar{y})^2}}
\]</span></p>
<p>Here, <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> denotes the mean of <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> respectively across <span class="math inline">\(i= 1,\ldots,n\)</span> observations.The plot below displays scatterplots for hypothetical numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> simulated to have different levels of correlation.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/correlation2-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Differing levels of correlation between variables.</figcaption></figure>
</div>
</div>
</div>
<p>The correlation coefficient can be computed in R using the <code>get_correlation</code> function from the <code>moderndive</code> package. The function requires two numerical variables separated by <code>~</code> (or ‘tilde’), much like the formula syntax, such that the outcome variable <code>score</code> is put on the left-hand-side of the formula, and the explanatory variable <code>bty_avg</code> is placed on the right-hand-side of the formula:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">evals.scores</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="moderndive.github.io/moderndive/reference/get_correlation.html">get_correlation</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">score</span> <span class="op">~</span> <span class="va">bty_avg</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    cor
  &lt;dbl&gt;
1 0.187</code></pre>
</div>
</div>
<p>Here, we are given a correlation coefficient of 0.187 for the relationship between teaching (<code>score</code>) and beauty (<code>bty_avg</code>) scores. This suggests a rather <em>weakly positive</em> linear relationship between the two variables. There is some subjective interpretation surrounding correlation coefficients not very close to -1, 0, 1. The table below provides a rough guide as to the verbal interpretation of a correlation coefficient.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 59%">
</colgroup>
<thead><tr class="header">
<th>Correlation coefficient</th>
<th>Verbal interpretation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.90 to 1.00 (-0.90 to -1.00)</td>
<td>Very strong positive (negative) correlation</td>
</tr>
<tr class="even">
<td>0.70 to 0.90 (-0.70 to -0.90)</td>
<td>Strong positive (negative) correlation</td>
</tr>
<tr class="odd">
<td>0.50 to 0.70 (-0.50 to -0.70)</td>
<td>Moderate positive (negative) correlation</td>
</tr>
<tr class="even">
<td>0.30 to 0.50 (-0.30 to -0.50)</td>
<td>Weak positive (negative) correlation</td>
</tr>
<tr class="odd">
<td>0.00 to 0.30 (0.00 to -0.30)</td>
<td>Very weak positive (negative) correlation</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>cor</code> function can also be used to compute the correlation coefficient. For more details type <code><a href="https://rdrr.io/r/stats/cor.html">?cor</a></code> into the R console.</p>
</div>
</div>
<p>The next step in our exploratory data analysis is to visualise the data using appropriate plotting techniques. Here, a scatterplot is appropriate since both <code>score</code> and <code>bty_avg</code> are numerical variables:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">evals.scores</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">bty_avg</span>, y <span class="op">=</span> <span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/correlationplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Relationship between teaching and beauty scores.</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The outcome variable should always be plotted on the y-axis.</p>
</div>
</div>
<p>What can we observe from the scatterplot? Well, here it can be hard to see the weakly positive linear relationship suggested by the correlation coefficient (0.187), which is why our correlation coefficient is considered <em>very weak</em> in the verbal interpretation.</p>
<p>Additionally, as our numerical variables are averages of integers (or whole numbers), a lot of the values will be plotted on top of one another. Remember, from Session 1, that this is referred to as <strong>over-plotting</strong>, and can be alleviated by slightly nudging (<strong>jittering</strong>) the points in a random direction. For example, let’s look at the three points in the top-right of the scatterplot that have a beauty score slightly less than 8. Are there really only three values plotted there, or are there more that we cannot see due to over-plotting? Let’s find out by adding some jitter to the plot:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/correlation5-1.png" class="img-fluid figure-img" width="1344"></p>
<figcaption>Comparing regular and jittered scatterplots.</figcaption></figure>
</div>
</div>
</div>
<p>From the jittered scatterplot we can see that:</p>
<ol type="1">
<li>There are actually more than just three points plotted in the top-right; and</li>
<li>There are more instructors with a beauty score between 3 and 4.5 than originally appears due to over-plotting.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jittering does not actually change the values within a data set, it is merely a tool for visualisation purposes. Hence, we shall continue on with plotting the original data.</p>
</div>
</div>
</section><section id="formal-analysis" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="formal-analysis">
<span class="header-section-number">3.3</span> Formal analysis</h2>
<p>After completing an exploratory data analysis the next step is to perform a <strong>formal analysis</strong> on the data. This involves constructing an appropriate statistical model from the information gathered during the exploratory data analysis step. Here, we shall be fitting a simple linear regression model to the data on teaching and beauty scores, where our objective is to acquire the best fitting regression line. This is done by finding estimates of the intercept (<span class="math inline">\(\alpha\)</span>) and slope (<span class="math inline">\(\beta\)</span>) which give us the best-fitting line to the data. This can be done in R using the <code>lm</code> function. However, in this module we will explore the <code>tidymodels</code> R-package which contains a wide variety of modeling approaches. To fit a linear regression model we can use the <code>linear_reg()</code> function.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>linear_reg()</code> function uses the <code>lm</code> engine as the default estimation approach. However, different estimations methods that wou will cover in future course are also available (see <code>?linear_reg()</code> for a complete list of the available engines).</p>
</div>
</div>
<p>Once we declare the engine we want to use (in this case we will use the default settings), the model can be estimated by using the <code>fit()</code> function as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">bty_avg</span>, data <span class="op">=</span> <span class="va">evals.scores</span><span class="op">)</span></span>
<span><span class="va">model</span><span class="op">$</span><span class="va">fit</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = score ~ bty_avg, data = data)

Coefficients:
(Intercept)      bty_avg  
    3.88034      0.06664  </code></pre>
</div>
</div>
<p>The fitted model (the <code>lm</code> object in this case) can be accessed by calling <code>$fit</code> to the model we built. This tells us that our best-fitting line to the data is:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = \widehat{\alpha} + \widehat{\beta} x_i = 3.88034 + 0.06664 \cdot \mbox{bty\_avg},\]</span> where</p>
<ul>
<li>
<span class="math inline">\(\widehat{\alpha} = 3.88034\)</span> is the intercept coefficient and means that, for any instructor with a <code>bty_avg = 0</code>, their average teaching <code>score</code> would be 3.8803. Note that <code>bty_avg = 0</code> is not actually possible as <code>bty_avg</code> is an average of beauty scores ranging between 1 and 10.</li>
<li>
<span class="math inline">\(\widehat{\beta} = 0.06664\)</span> is the slope coefficient associated with the exploratory variable <code>bty_avg</code>, and summarises the relationship between <code>score</code> and <code>bty_avg</code>. That is, as <code>bty_avg</code> increases, so does <code>score</code>, such that
<ul>
<li>For every 1 unit increase in <code>bty_avg</code>, there is an associated increase of, on average, 0.06664 units of <code>score</code>.</li>
</ul>
</li>
</ul>
<p>We can ask for a model summary using the <code>tidy</code> function that will return the output in a <code>data.frame</code> format:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tidy</span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   3.88      0.0761     51.0  1.56e-191
2 bty_avg       0.0666    0.0163      4.09 5.08e-  5</code></pre>
</div>
</div>
<p>Finally, we can superimpose our best-fitting line onto our scatterplot to see how it fits through the points using the <code>geom_smooth</code> function as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">evals.scores</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">bty_avg</span>, y <span class="op">=</span> <span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Beauty Score"</span>, y <span class="op">=</span> <span class="st">"Teaching Score"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Relationship of teaching and beauty scores"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/lm2-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Relationship between teaching and beauty scores with regression line superimposed.</figcaption></figure>
</div>
</div>
</div>
<p>Now that we have fitted our simple linear regression model to the data, how do we use it to obtain information on individual data points? This can be done by looking at the <strong>fitted values</strong>. For example, let’s say we are interested in looking at the 21st instructor who has the following teaching and beauty scores:</p>
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: right;"><code>score</code></th>
<th style="text-align: right;"><code>bty_avg</code></th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">7.33</td>
</tr></tbody>
</table>
<p>What would the <code>score</code> be on our best-fitting line for this instructor with a <code>bty_avg</code> of 7.33? We simply plug the instructor’s <code>bty_avg</code> into our regression model:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = 3.88034 + 0.06664 \cdot \mbox{bty\_avg} = 3.88034 + 0.06664 \cdot 7.33 = 4.369,\]</span> The regression model gives our instructor a <code>score</code> of 4.369. However, we know the <code>score</code> of the instructor is 4.9 meaning that our model was out by 0.531. This is known as the <strong>residual</strong> (<span class="math inline">\(\epsilon\)</span>) and can be thought of as the error or <em>lack of fit</em> of the regression line. In this case, the residual is given by:</p>
<p><span class="math display">\[ \widehat{\epsilon} = y - \widehat{y} = 4.9 - 4.369 = 0.531.\]</span>This is essentially the distance between the fitted regression line and the observed (true) value. This can be seen on the following scatterplot:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/lm3-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Example of observed value, fitted value, and residual.</figcaption></figure>
</div>
</div>
</div>
<p>where</p>
<ul>
<li>the red circle is the observed (true) <code>score</code> (<span class="math inline">\(y=4.9\)</span>) of the instructor;</li>
<li>the red square is the fitted value (<span class="math inline">\(\widehat{y} = 4.369\)</span>) from the regression line; and</li>
<li>the blue arrow is the distance between the observed and fitted values, that is, the residual.</li>
</ul>
<p>To obtain the fitted values and residuals for all instructors within the data set we can use the <code>get_regression_points</code> function:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">regression.points</span> <span class="op">&lt;-</span> <span class="fu"><a href="moderndive.github.io/moderndive/reference/get_regression_points.html">get_regression_points</a></span><span class="op">(</span><span class="va">model</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="va">regression.points</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 463 × 5
      ID score bty_avg score_hat residual
   &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1     1   4.7    5         4.21    0.486
 2     2   4.1    5         4.21   -0.114
 3     3   3.9    5         4.21   -0.314
 4     4   4.8    5         4.21    0.586
 5     5   4.6    3         4.08    0.52 
 6     6   4.3    3         4.08    0.22 
 7     7   2.8    3         4.08   -1.28 
 8     8   4.1    3.33      4.10   -0.002
 9     9   3.4    3.33      4.10   -0.702
10    10   4.5    3.17      4.09    0.409
# ℹ 453 more rows</code></pre>
</div>
</div>
<p>The table provides us with information on the:</p>
<ul>
<li>
<code>score</code>: the observed value of the outcome variable <span class="math inline">\(y\)</span>;</li>
<li>
<code>bty_avg</code>: the values of the explanatory variable <span class="math inline">\(x\)</span>;</li>
<li>
<code>score_hat</code>: the values of the fitted values <span class="math inline">\(\widehat{y}\)</span>; and</li>
<li>
<code>residual</code>: the residuals <span class="math inline">\(y - \widehat{y}\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Residuals and fitted values can also be obtained directly from the fitted <code>model</code> object:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span> <span class="va">model_output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>score_hat  <span class="op">=</span> <span class="va">model</span><span class="op">$</span><span class="va">fit</span><span class="op">$</span><span class="va">fitted.values</span>,</span>
<span>                            residuals <span class="op">=</span> <span class="va">model</span><span class="op">$</span><span class="va">fit</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span>
<span> <span class="va">model_output</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  score_hat  residuals
1  4.213523  0.4864769
2  4.213523 -0.1135231
3  4.213523 -0.3135231
4  4.213523  0.5864769
5  4.080249  0.5197509
6  4.080249  0.2197509</code></pre>
</div>
</div>
</div>
</div>
</section><section id="assessing-model-fit" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="assessing-model-fit">
<span class="header-section-number">3.4</span> Assessing model fit</h2>
<p>When we fit a simple linear regression model there are five main assumptions that we need to hold true in order for the model to be an appropriate fit to the data. These assumptions are:</p>
<ol type="1">
<li>The deterministic part of the model captures all the non-random structure in the data, i.e.&nbsp;the residuals have mean zero.</li>
<li>The scale of the variability of the residuals is constant at all values of the explanatory variables (<em>homoscedasticity</em>).</li>
<li>The residuals are normally distributed.</li>
<li>The residuals are independent.</li>
<li>The values of the explanatory variables are recorded without error.</li>
</ol>
<p>One way we can check our first assumption is to plot the residuals (<code>residuals</code>) against the explanatory variable (<code>bty_avg</code>). From this we should be able to check that the explanatory variable has a linear relationship with the outcome variable (<code>score</code>). We can plot the residuals against our explanatory variable using:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">bty_avg</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Beauty Score"</span>, y <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/lm6-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuals against beauty score.</figcaption></figure>
</div>
</div>
</div>
<p>Ideally, for the first assumption to hold we should observe the following:</p>
<ul>
<li>There should be no systematic pattern, i.e.&nbsp;the residuals should appear randomly scattered.</li>
<li>The residuals should have mean zero. That is, they should be evenly scattered above and below the zero line. This is because the regression model will overestimate some of the fitted values, but it will also underestimate some, and hence, on average, they should even out to have mean zero.</li>
</ul>
<p>We can examine our first two assumptions by also plotting the residuals against the fitted values as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">score_hat</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Fitted values"</span>, y <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/lm7-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuals against fitted values.</figcaption></figure>
</div>
</div>
</div>
<p>From the plot of the residuals against the fitted values we want to examine whether:</p>
<ul>
<li>The residuals have mean zero.</li>
<li>If the residuals have constant variance across all levels of the fitted values. That is, the range (or spread) of the residuals should be similar across all levels of the fitted values and display no obvious changes in variability.</li>
</ul>
<p>To assess our third assumption that the residuals are normally distributed we can simply plot a histogram of the residuals:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">0.25</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/lm9-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogram of residuals.</figcaption></figure>
</div>
</div>
</div>
<p>Ideally, for the assumption of normally distributed residuals, the histogram should be bell-shaped and centred at zero, i.e.&nbsp;the residuals have mean zero. However, in practice this will almost never be the case, and as such, like the plots of the residuals, there is some subjectivity in whether you believe the assumptions hold. For instance, here we can see that the histogram is slightly skewed to the left in that the distribution has a longer tail to the left. However, in my opinion, this is not of much concern as the histogram appears to be relatively symmetrical and bell-shaped, and as such the assumption of normally distributed random errors appears valid in this case.</p>
<p>Finally, assumptions 4.&nbsp;and 5.&nbsp;are often justified on the basis of the experimental context and are not formally examined.</p>
</section></section><section id="simple-linear-regression-with-one-categorical-explanatory-variable" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Simple linear regression with one categorical explanatory variable</h1>
<p>Here, we will fit a simple linear regression model were the explanatory variable is categorical. A <strong>categorical variable</strong> is a variable of a fixed number of possible values, assigning units to particular groups (or categories) based on qualitative properties.</p>
<p>We shall examine the <code>gapminder</code> data set from the <code>gapminder</code> library. This is a data set on life expectancy across various countries around the world. We will explore life expectancy and its potential differences:</p>
<ul>
<li>Between continents: Does life expectancy vary, on average, between the five continents of the world?; and</li>
<li>Within continents: Does life expectancy vary, on average, within the five continents of the world?</li>
</ul>
<p>Thus, we will be looking at:</p>
<ul>
<li>life expectancy as our numerical outcome variable <span class="math inline">\(y\)</span>; and</li>
<li>the continent a country is within as our categorical variable <span class="math inline">\(x\)</span>.</li>
</ul>
<section id="exploratory-data-analysis-1" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="exploratory-data-analysis-1">
<span class="header-section-number">4.1</span> Exploratory data analysis</h2>
<p>Let’s examine a subset of the <code>gapminder</code> data set relating to the year 2007. That is, we use the <code>filter</code> function to choose only the observations pertaining to 2007, and then <code>select</code> the variables we are interested in:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gapminder2007</span> <span class="op">&lt;-</span> <span class="va">gapminder</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">year</span> <span class="op">==</span> <span class="fl">2007</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">country</span>, <span class="va">continent</span>, <span class="va">lifeExp</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The new data set can be examined using either the <code>View</code> or <code>glimpse</code> functions, i.e.<br></p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">gapminder2007</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 142
Columns: 3
$ country   &lt;fct&gt; "Afghanistan", "Albania", "Algeria", "Angola", "Argentina", …
$ continent &lt;fct&gt; Asia, Europe, Africa, Africa, Americas, Oceania, Europe, Asi…
$ lifeExp   &lt;dbl&gt; 43.828, 76.423, 72.301, 42.731, 75.320, 81.235, 79.829, 75.6…</code></pre>
</div>
</div>
<p>Here, we can see that both <code>country</code> and <code>continent</code> are factors (<code>fct</code>), which is how R stores categorical variables. Similarly to our previous exploratory data analysis, we can obtain summary statistics using the <code>skim</code> function. First, let’s take a look at the life expectancy (<code>lifeExp</code>) and <code>continent</code> variables:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gapminder2007</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">continent</span>, <span class="va">lifeExp</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">select(gapminder2007, con…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">142</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 38%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Afr: 52, Asi: 33, Eur: 30, Ame: 25</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">lifeExp</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">67.01</td>
<td style="text-align: right;">12.07</td>
<td style="text-align: right;">39.61</td>
<td style="text-align: right;">57.16</td>
<td style="text-align: right;">71.94</td>
<td style="text-align: right;">76.41</td>
<td style="text-align: right;">82.6</td>
<td style="text-align: left;">▂▃▃▆▇</td>
</tr></tbody>
</table>
</div>
</div>
<p>The summary output for the numerical outcome variable <code>lifeExp</code> is the same as we have seen previously. However, for the categorical variable <code>continent</code> we obtain:</p>
<ul>
<li>
<code>n_unique</code>: the number of levels (or categories) of the variable, i.e.&nbsp;the number of continents.</li>
<li>
<code>top_counts</code>: the top counts from the top categories.</li>
<li>
<code>ordered</code>: whether the variable is <em>ordinal</em> or not. That is, whether or not the ordering of the categories matter.</li>
</ul>
<p>We can summarise any differences in life expectancy by continent by taking a look at the median and mean life expectancies of each continent using the <code>summarize</code> functions as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lifeExp.continent</span> <span class="op">&lt;-</span> <span class="va">gapminder2007</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>median <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">lifeExp</span><span class="op">)</span>, mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">lifeExp</span><span class="op">)</span>,.by <span class="op">=</span> <span class="va">continent</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  continent median  mean
  &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 Asia        72.4  70.7
2 Europe      78.6  77.6
3 Africa      52.9  54.8
4 Americas    72.9  73.6
5 Oceania     80.7  80.7</code></pre>
</div>
</div>
<p>Boxplots are often used when examining the distribution of a numerical outcome variable across different levels of a categorical variable:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">gapminder2007</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">continent</span>, y <span class="op">=</span> <span class="va">lifeExp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Continent"</span>, y <span class="op">=</span> <span class="st">"Life expectancy (years)"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Life expectancy by continent"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/gap6-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Life expectancy by continent in 2007.</figcaption></figure>
</div>
</div>
</div>
<p>Here, we can see that the middle 50% of the life expectancy distribution of Africa is much smaller than, and does not overlap with, the middle 50% of the remaining four continents, while the country with the highest life expectancy in Africa is less than all countries in Oceania. Speaking of Oceania, there is almost no variability (or spread) in life expectancy in this continent, however that may well be because it consists of only two countries (Australia and New Zealand). There is more variability in life expectancy in the continents of Africa and Asia.</p>
</section><section id="formal-analysis-1" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="formal-analysis-1">
<span class="header-section-number">4.2</span> Formal analysis</h2>
<p>When examining the relationship between a numerical outcome variable <span class="math inline">\(y\)</span> and a categorical explanatory variable <span class="math inline">\(x\)</span>, we are not just looking to find the best-fitting line to the data as before, but are examining relative differences to a baseline category. For example, the table below displays the mean life expectancy of each continent, as well as the differences between the means of each continent and Africa. Now, in comparison with Africa we can see that the mean life expectancy of the other continents is around 18-26 years greater than that of Africa.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">continent</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">mean vs Africa</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">54.81</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Americas</td>
<td style="text-align: right;">73.61</td>
<td style="text-align: right;">18.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.73</td>
<td style="text-align: right;">15.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.65</td>
<td style="text-align: right;">22.84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">80.72</td>
<td style="text-align: right;">25.91</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now let us fit our regression model to the data, where <code>lifeExp</code> is our outcome variable <span class="math inline">\(y\)</span> and <code>continent</code> is our categorical explanatory variable <span class="math inline">\(x\)</span>:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lifeExp.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">lifeExp</span> <span class="op">~</span> <span class="va">continent</span>, data <span class="op">=</span> <span class="va">gapminder2007</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term              estimate std.error statistic  p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)           54.8      1.03     53.4  1.23e-93
2 continentAmericas     18.8      1.80     10.4  3.74e-19
3 continentAsia         15.9      1.65      9.67 3.41e-17
4 continentEurope       22.8      1.70     13.5  7.10e-27
5 continentOceania      25.9      5.33      4.86 3.12e- 6</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For now we will ignore the last three columns of the regression table and only focus on the estimate column.</p>
</div>
</div>
<p>We obtain five estimates: the <code>intercept</code> term and four others relating to the continents (<code>continentAmericas</code>, <code>continentAsia</code>, <code>continentEurope</code> and <code>continentOceania</code>), such that our regression equation is given as:</p>
<p><span class="math display">\[\widehat{\mbox{life exp}} = \widehat{\alpha} + \widehat{\beta}_{\mbox{Amer}} \cdot \mathbb{I}_{\mbox{Amer}}(x) + \widehat{\beta}_{\mbox{Asia}} \cdot \mathbb{I}_{\mbox{Asia}}(x) + \widehat{\beta}_{\mbox{Euro}} \cdot \mathbb{I}_{\mbox{Euro}}(x) + \widehat{\beta}_{\mbox{Ocean}} \cdot \mathbb{I}_{\mbox{Ocean}}(x),\]</span> where</p>
<ul>
<li><p>the intercept <span class="math inline">\(\widehat{\alpha}\)</span> is the mean life expectancy for our baseline category Africa;</p></li>
<li><p><span class="math inline">\(\widehat{\beta}_{\mbox{continent}}\)</span> is the difference in the mean life expectancy of a given continent relative to the baseline category Africa; and</p></li>
<li>
<p><span class="math inline">\(\mathbb{I}_{\mbox{continent}}(x)\)</span> is an indicator function such that</p>
<p><span class="math display">\[\mathbb{I}_{\mbox{continent}}(x)=\left\{
            \begin{array}{ll}
              1 ~~~ \mbox{if country} ~ x ~ \mbox{is in the continent},\\
              0 ~~~ \mbox{Otherwise}.\\
            \end{array}
          \right.\]</span></p>
</li>
</ul>
<p>Essentially, the estimates for each continent are known as <em>offsets</em> relative to the baseline category (Africa in this case). For example, the mean life expectancy for Africa is simply equal to the intercept term <span class="math inline">\(\widehat{\alpha} = 54.8\)</span>. However, the mean life expectancy for Asia is:</p>
<p><span class="math display">\[\widehat{\alpha} + \widehat{\beta}_{\mbox{Asia}} \cdot \mathbb{I}_{\mbox{Asia}}(x) = 54.8 + 15.9 \cdot 1 = 70.7 \]</span></p>
<p>If we just look at a <span class="math inline">\(\widehat{\beta}_{\mbox{continent}}\)</span> on their own, then we would interpret these coefficients in relative terms with respect to the baseline category. E.g., looking at <span class="math inline">\(\widehat{\beta}_{\mbox{Asia}}=15.9\)</span> , we would say that the life expectancy in Asia is on average 15.9 years greater than in Africa.</p>
</section><section id="assessing-model-fit-1" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="assessing-model-fit-1">
<span class="header-section-number">4.3</span> Assessing model fit</h2>
<p>What do the fitted values <span class="math inline">\(\widehat{y}\)</span> and the residuals <span class="math inline">\(y - \widehat{y}\)</span> correspond to when we are dealing with a categorical explanatory variable? Let’s explore the <code>gapminder2007</code> data set in order to understand how they work.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 3
   country     continent lifeExp
   &lt;fct&gt;       &lt;fct&gt;       &lt;dbl&gt;
 1 Afghanistan Asia         43.8
 2 Albania     Europe       76.4
 3 Algeria     Africa       72.3
 4 Angola      Africa       42.7
 5 Argentina   Americas     75.3
 6 Australia   Oceania      81.2
 7 Austria     Europe       79.8
 8 Bahrain     Asia         75.6
 9 Bangladesh  Asia         64.1
10 Belgium     Europe       79.4
# ℹ 132 more rows</code></pre>
</div>
</div>
<p>Here, we see the life expectancy of each country and the continent they are from. For example, let’s remember the life expectancies of Afghanistan (43.8) and Bahrain (75.6). Now, we can obtain the fitted values and residuals in the same way we did previously:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">regression_points</span> <span class="op">&lt;-</span> <span class="fu"><a href="moderndive.github.io/moderndive/reference/get_regression_points.html">get_regression_points</a></span><span class="op">(</span><span class="va">lifeExp.model</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 5
      ID lifeExp continent lifeExp_hat residual
   &lt;int&gt;   &lt;dbl&gt; &lt;fct&gt;           &lt;dbl&gt;    &lt;dbl&gt;
 1     1    43.8 Asia             70.7  -26.9  
 2     2    76.4 Europe           77.6   -1.23 
 3     3    72.3 Africa           54.8   17.5  
 4     4    42.7 Africa           54.8  -12.1  
 5     5    75.3 Americas         73.6    1.71 
 6     6    81.2 Oceania          80.7    0.516
 7     7    79.8 Europe           77.6    2.18 
 8     8    75.6 Asia             70.7    4.91 
 9     9    64.1 Asia             70.7   -6.67 
10    10    79.4 Europe           77.6    1.79 
# ℹ 132 more rows</code></pre>
</div>
</div>
<p>The first row of the regression table corresponds to the observed life expectancy (<code>lifeExp</code>), fitted value (<code>lifeExp_hat</code>) and the residual error (<code>residual</code>) for Afghanistan. Here, we see that the fitted value (<code>lifeExp_hat = 70.7</code>) is much greater than the life expectancy of Afghanistan (<code>lifeExp = 43.8</code>) with a <code>residual = -26.9</code>. Now, for Bahrain (<code>ID = 8</code>) we also have the same fitted value (<code>lifeExp_hat = 70.7</code>). This is because the fitted values for each <code>country</code> correspond to the mean life expectancy for that <code>continent</code>. Hence, all countries in Africa have the fitted value <code>lifeExp_hat = 70.7</code>, while all countries in Europe have the fitted value <code>lifeExp_hat = 77.6</code>. The <code>residual</code> error in this case is then how much a country deviates from the mean life expectancy of its respective continent.</p>
<p>For assessing the assumptions surrounding the residuals for a categorical explanatory variable, we can plot the residuals for each continent:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression_points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">continent</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Continent"</span>, y <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/gap14-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuals over continent.</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have jittered the points for each continent in order to see the residuals for each country more clearly.</p>
</div>
</div>
<p>Here, we see that there is an even spread of the residuals above and below the zero line for each continent, and hence our assumption that the residuals have mean zero appears valid. There is an outlier observed for Asia with a large negative residual (relating to Afghanistan).</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>What about the homoscedasticity assumption, is it valid?</p>
<div id="radio_RJPOWLUNFL" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_RJPOWLUNFL" value=""><span>yes, residuals are not heteroscedastic</span></label><label><input type="radio" autocomplete="off" name="radio_RJPOWLUNFL" value=""><span>no, there is an unbalanced number of residuals per country</span></label><label><input type="radio" autocomplete="off" name="radio_RJPOWLUNFL" value=""><span>yes, residuals show an even spread across countries</span></label><label><input type="radio" autocomplete="off" name="radio_RJPOWLUNFL" value="answer"><span>no, the spread of the residuals is not even across countries</span></label>
</div>
</div>
</div>
<p>To check that the residual errors are normally distributed, we plot a histogram of them:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression_points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">5</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/gap15-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogram of residuals.</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="multiple-regression-with-two-numerical-explanatory-variables" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Multiple regression with two numerical explanatory variables</h1>
<p>In the last sections we introduced regression modelling where we modelled the relationship between an outcome variable <span class="math inline">\(y\)</span> and a single explanatory variable <span class="math inline">\(x\)</span>, which was either a numerical or categorical variable. Here, we shall now examine fitting regression models with more than one explanatory variable. This is known as <strong>multiple regression</strong>.</p>
<p>When fitting regression models with multiple explanatory variables, the interpretation of an explanatory variable is made in association with the other variables. For example, if we wanted to model income then we may consider an individuals level of education, and perhaps the wealth of their parents. Then, when interpreting the effect an individuals level of education has on their income, we would also be considering the effect of the wealth of their parents simultaneously, as these two variables are likely to be related.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Additional information and examples can be found in <a href="https://moderndive.com/7-multiple-regression.html">Chapter 7</a> of <a href="https://moderndive.com/index.html">An Introduction to Statistical and Data Science via R</a>.</p>
</div>
</div>
<p>We shall examine a data set within the <code>ISLR</code> package, which is an accompanying R package related to the textbook <a href="http://www-bcf.usc.edu/~gareth/ISL/">An Introduction to Statistical Learning with Applications in R</a>. We will take a look at the <code>Credit</code> data set, which consists of predictions made on the credit card balance of 400 individuals, were the predictions are based on information relating to income, credit limit and the level of education of an individual.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.statlearning.com">ISLR</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"Credit"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a simulated data set and is not based on credit card balances of actual individuals.</p>
</div>
</div>
<p>The regression model we will be considering contains the following variables:</p>
<ul>
<li>the numerical outcome variable <span class="math inline">\(y\)</span>, the credit card balance of an individual; and</li>
<li>two explanatory variables <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, which are an individuals credit limit and income (in thousands of dollars), respectively.</li>
</ul>
<section id="exploratory-data-analysis-2" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="exploratory-data-analysis-2">
<span class="header-section-number">5.1</span> Exploratory data analysis</h2>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Task
</div>
</div>
<div class="callout-body-container callout-body">
<p>Start by subsetting the <code>Credit</code> data set so that we only have the variables we are interested in, that is, <code>Balance</code>, <code>Limit</code> and <code>Income</code>. Note, it is best to give your new data set a different name than Credit as to not overwrite the original <code>Credit</code> data set. Define a new data set named <code>Cred</code> containing only the aforementioned variables.</p>
<div class="webex-solution">
<button>
Take a hint
</button>
<p>You can use the <code>select</code> function from the <code>dplyr</code> package to select different variables in a data frame.</p>
</div>
<div class="cell" data-webex.hide="Click here to see the solution">
<div class="webex-solution">
<button>
Click here to see the solution
</button>
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Cred</span> <span class="op">=</span> <span class="va">Credit</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Balance</span>,<span class="va">Limit</span>,<span class="va">Income</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</div>
</div>
<p>ke a look at summary statistics relating to our newly created data set using the <code>skim</code> function:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Cred</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Cred</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Balance</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">520.02</td>
<td style="text-align: right;">459.76</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">68.75</td>
<td style="text-align: right;">459.50</td>
<td style="text-align: right;">863.00</td>
<td style="text-align: right;">1999.00</td>
<td style="text-align: left;">▇▅▃▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Limit</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4735.60</td>
<td style="text-align: right;">2308.20</td>
<td style="text-align: right;">855.00</td>
<td style="text-align: right;">3088.00</td>
<td style="text-align: right;">4622.50</td>
<td style="text-align: right;">5872.75</td>
<td style="text-align: right;">13913.00</td>
<td style="text-align: left;">▆▇▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Income</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.22</td>
<td style="text-align: right;">35.24</td>
<td style="text-align: right;">10.35</td>
<td style="text-align: right;">21.01</td>
<td style="text-align: right;">33.12</td>
<td style="text-align: right;">57.47</td>
<td style="text-align: right;">186.63</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now that we are looking at the relationship between an outcome variable and multiple explanatory variables, we need to examine the correlation between each of them. We can examine the correlation between <code>Balance</code>, <code>Limit</code> and <code>Income</code> by creating a table of correlations as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Cred</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>          Balance     Limit    Income
Balance 1.0000000 0.8616973 0.4636565
Limit   0.8616973 1.0000000 0.7920883
Income  0.4636565 0.7920883 1.0000000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why are the diagonal components of our correlation table all equal to 1?</p>
<div id="radio_JXNMVDFCAM" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_JXNMVDFCAM" value=""><span>because variables have been standardized to have an unit variance</span></label><label><input type="radio" autocomplete="off" name="radio_JXNMVDFCAM" value="answer"><span>because they are the correlation of a column with itself</span></label><label><input type="radio" autocomplete="off" name="radio_JXNMVDFCAM" value=""><span>because we have a diagonal covariance-variance matrix</span></label>
</div>
</div>
</div>
<p>From our correlation table we can see that the correlation between our two explanatory variables is 0.792, which is a strong positive linear relationship. Hence, we say there is a high degree of <em>collinearity</em> between our explanatory variables.</p>
<p><strong>Collinearity</strong> (or <strong>multicollinearity</strong>) occurs when an explanatory variable within a multiple regression model can be linearly predicted from the other explanatory variables with a high level of accuracy. For example, in this case, since <code>Limit</code> and <code>Income</code> are highly correlated, we could take a good guess as to an individual’s <code>Income</code> based on their <code>Limit</code>. That is, having one or more highly correlated explanatory variables within a multiple regression model essentially provides us with redundant information. Normally, we would remove one of the highly correlated explanatory variables, however, for the purpose of this example we shall ignore the potential issue of collinearity and carry on. You may want to use the <code>pairs</code> function or the <code>ggpairs</code> function from the <code>GGally</code> package to look at potential relationships between all of the variables within a data set.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we have several potential explanatory variables a model selection technique can help to identify which explanatory variables are significant predictors (in addition to the others) and which variables should be removed from the model. One procedure that can be used is <strong>stepwise regression</strong>, which implements an automatic procedure for choosing which explanatory variables should be included within the final model. A common stepwise procedure compares models using the model fit criterion <strong>Akaike Information Criterion</strong> (AIC) and can be implemented in R using the <code>stepAIC</code> function from the <code>MASS</code> library. This procedure allows for forward selection and backward selection (or both), where forward selection starts with the simplest model before iteratively including one explanatory variable at a time until the AIC reaches a minimum. The backward selection approach starts with the most complex model before removing one explanatory variable at a time until the minimium AIC is achieved. We will cover more of this in the next session.</p>
</div>
</div>
<p>Let’s now produce scatterplots of the relationship between the outcome variable and the explanatory variables. First, we shall look at the scatterplot of <code>Balance</code> against <code>Limit</code>:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Cred</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Limit</span>, y <span class="op">=</span> <span class="va">Balance</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Credit limit (in $)"</span>, y <span class="op">=</span> <span class="st">"Credit card balance (in $)"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Relationship between balance and credit limit"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/scat1-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>Relationship between balance and credit limit.</figcaption></figure>
</div>
</div>
</div>
<p>Now, let’s look at a scatterplot of <code>Balance</code> and <code>Income</code>:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Cred</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Income</span>, y <span class="op">=</span> <span class="va">Balance</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Income (in $1000)"</span>, y <span class="op">=</span> <span class="st">"Credit card balance (in $)"</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Relationship between balance and income"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/scat2-1.png" class="img-fluid figure-img" style="width:64.0%"></p>
<figcaption>Relationship between balance and income.</figcaption></figure>
</div>
</div>
</div>
<p>The two scatterplots above focus on the relationship between the outcome variable <code>Balance</code> and each of the explanatory variables independently. In order to get an idea of the relationship between all three variables we can use the <code>plot_ly</code> function within the <code>plotly</code> library to plot a 3-dimensional scatterplot as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://plotly-r.com">plotly</a></span><span class="op">)</span></span>
<span><span class="fu">plot_ly</span><span class="op">(</span><span class="va">Cred</span>, x <span class="op">=</span> <span class="op">~</span><span class="va">Income</span>, y <span class="op">=</span> <span class="op">~</span><span class="va">Limit</span>, z <span class="op">=</span> <span class="op">~</span><span class="va">Balance</span>,</span>
<span>        type <span class="op">=</span> <span class="st">"scatter3d"</span>, mode <span class="op">=</span> <span class="st">"markers"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>When we fitting our regression model with just a single covariate we looked at the <em>best-fitting line</em>. However, now that we have more than one explanatory variable, we are looking at the <em>best-fitting plane</em>, which is a 3-dimensional generalisation of the best-fitting line.</p>
</section><section id="formal-analysis-2" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="formal-analysis-2">
<span class="header-section-number">5.2</span> Formal analysis</h2>
<p>The multiple regression model we will be fitting to the credit balance data is given as:</p>
<p><span class="math display">\[y_i = \alpha + \beta_1 x_{1i} + \beta_2 x_{2i} + \epsilon_i, ~~~~ \epsilon \sim N(0, \sigma^2),\]</span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span> is the balance of the <span class="math inline">\(i^{th}\)</span> individual;</li>
<li>
<span class="math inline">\(\alpha\)</span> is the intercept and positions the best-fitting plane in 3D space;</li>
<li>
<span class="math inline">\(\beta_1\)</span> is the coefficient for the first explanatory variable <span class="math inline">\(x_1\)</span>;</li>
<li>
<span class="math inline">\(\beta_2\)</span> is the coefficient for the second explanatory variable <span class="math inline">\(x_2\)</span>; and</li>
<li>
<span class="math inline">\(\epsilon_i\)</span> is the <span class="math inline">\(i^{th}\)</span> random error component.</li>
</ul>
<p>Similarly to a simple linear regression, we use the <code>lm</code> function to fit the regression model and the <code>tidy</code> function to view our parameter estimates:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Balance.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span>  <span class="op">|&gt;</span>  <span class="fu">fit</span><span class="op">(</span><span class="va">Balance</span> <span class="op">~</span> <span class="va">Limit</span> <span class="op">+</span> <span class="va">Income</span>, data <span class="op">=</span> <span class="va">Cred</span><span class="op">)</span></span>
<span><span class="fu">tidy</span><span class="op">(</span><span class="va">Balance.model</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) -385.     19.5         -19.8 3.88e- 61
2 Limit          0.264   0.00588      45.0 7.72e-158
3 Income        -7.66    0.385       -19.9 1.26e- 61</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>To include multiple explanatory variables within a regression model we simply use the <code>+</code> sign, that is <code>Balance ~ Limit + Income</code>.</p>
</div>
</div>
<p>How do we interpret our model estimates defining the regression plane? They can be interpreted as follows:</p>
<ul>
<li>The <strong>intercept</strong> represents the credit card balance (<code>Balance</code>) of an individual who has $0 for both credit limit (<code>Limit</code>) and income (<code>Income</code>). However, the interpretation of the intercept in this case is somewhat limited as there are no individuals with $0 credit limit and income in the data set, with the smallest credit card balance being $0.</li>
<li>The coefficient for credit limit (<code>Limit</code>) tells us that, <em>taking all other variables in the model into account</em>, that there is an associated increase, on average, in credit card balance of $0.26.</li>
<li>Similarly, the coefficient for income (<code>Income</code>) tells us that, <em>taking all other variables in the model into account</em>, that there is an associated decrease, on average, in credit card balance of $7.66.</li>
</ul>
<p>What do you notice that is strange about our coefficient estimates given our exploratory data analysis? Well, from our scatterplots of credit card balance against both credit limit and income, we seen that there appeared to be a positive linear relationship. Then, why do we then get a negative coefficient for income (-7.66)? This is due to a phenomenon known as <strong>Simpson’s Paradox</strong>. This occurs when there are trends within different categories (or groups) of data, but that these trends disappear when the categories are grouped as a whole. For more details see <a href="https://moderndive.com/7-multiple-regression.html#simpsonsparadox">Section 7.3.2 of An Introduction to Statistical and Data Sciences in R</a>.</p>
</section><section id="assessing-model-fit-for-multiple-regression" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="assessing-model-fit-for-multiple-regression">
<span class="header-section-number">5.3</span> Assessing model fit for multiple regression</h2>
<p>Now we need to assess our model assumptions. Similarly to simple regression, our model assumptions are:</p>
<ol type="1">
<li>The deterministic part of the model captures all the non-random structure in the data, i.e.&nbsp;the residuals have mean zero.</li>
<li>The scale of the variability of the residuals is constant at all values of the explanatory variables.</li>
<li>The residuals are normally distributed.</li>
<li>The residuals are independent.</li>
<li>The values of the explanatory variables are recorded without error.</li>
</ol>
<p>First, we need to obtain the fitted values and residuals from our regression model:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">regression.points</span> <span class="op">&lt;-</span> <span class="fu"><a href="moderndive.github.io/moderndive/reference/get_regression_points.html">get_regression_points</a></span><span class="op">(</span><span class="va">Balance.model</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Recall that <code>get_regression_points</code> provides us with values of the:</p>
<ul>
<li>outcome variable <span class="math inline">\(y\)</span> (<code>Balance</code>);</li>
<li>explanatory variables <span class="math inline">\(x_1\)</span> (<code>Limit</code>) and <span class="math inline">\(x_2\)</span> (<code>Income</code>);</li>
<li>fitted values <span class="math inline">\(\widehat{y}\)</span>; and</li>
<li>the residual error (<span class="math inline">\(y - \widehat{y}\)</span>).</li>
</ul>
<p>We can assess our first two model assumptions by producing scatterplots of our residuals against each of our explanatory variables. First, let’s begin with the scatterplot of the residuals against credit limit:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Limit</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Credit limit (in $)"</span>, y <span class="op">=</span> <span class="st">"Residual"</span>, title <span class="op">=</span> <span class="st">"Residuals vs credit limit"</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/residplots1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuals vs credit limit.</figcaption></figure>
</div>
</div>
</div>
<p>Now, let’s plot a scatterplot of the residuals against income:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Income</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Income (in $1000)"</span>, y <span class="op">=</span> <span class="st">"Residual"</span>, title <span class="op">=</span> <span class="st">"Residuals vs income"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/residplots2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Residuals vs income.</figcaption></figure>
</div>
</div>
</div>
<p>We can also call the function&nbsp;<code>autoplot</code>&nbsp;form the&nbsp;<code>ggfortify</code>&nbsp;library to produce the standard diagnostic plots for a fitted linear regression model:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sinhrks/ggfortify">ggfortify</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">Balance.model</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>Which assumptions does each of the following plots address?</p>
</div>
</div>


</section></section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>