<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Week 3: Regression modelling part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./UofG_Coat_of_Arms.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/bootstrap-icons-1.11.1/all.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="include/webex.css">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./UofG.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Week 3: Regression modelling part 2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="./notes_24_25.html" aria-current="page"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Week Tasks</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li>
<a href="#regression-modelling-with-one-numerical-and-one-categorical-explanatory-variable" id="toc-regression-modelling-with-one-numerical-and-one-categorical-explanatory-variable" class="nav-link active" data-scroll-target="#regression-modelling-with-one-numerical-and-one-categorical-explanatory-variable"><span class="header-section-number">1</span> Regression modelling with one numerical and one categorical explanatory variable</a>
  <ul class="collapse">
<li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">1.1</span> Exploratory data analysis</a></li>
  <li><a href="#multiple-regression-parallel-slopes-model" id="toc-multiple-regression-parallel-slopes-model" class="nav-link" data-scroll-target="#multiple-regression-parallel-slopes-model"><span class="header-section-number">1.2</span> Multiple regression: parallel slopes model</a></li>
  <li><a href="#multiple-regression-interaction-model" id="toc-multiple-regression-interaction-model" class="nav-link" data-scroll-target="#multiple-regression-interaction-model"><span class="header-section-number">1.3</span> Multiple regression: interaction model</a></li>
  <li><a href="#assessing-model-fit" id="toc-assessing-model-fit" class="nav-link" data-scroll-target="#assessing-model-fit"><span class="header-section-number">1.4</span> Assessing model fit</a></li>
  </ul>
</li>
  <li>
<a href="#sample-statistics" id="toc-sample-statistics" class="nav-link" data-scroll-target="#sample-statistics"><span class="header-section-number">2</span> Sample statistics</a>
  <ul class="collapse">
<li><a href="#inference-using-sample-statistics" id="toc-inference-using-sample-statistics" class="nav-link" data-scroll-target="#inference-using-sample-statistics"><span class="header-section-number">2.1</span> Inference using sample statistics</a></li>
  </ul>
</li>
  <li>
<a href="#constructing-confidence-intervals" id="toc-constructing-confidence-intervals" class="nav-link" data-scroll-target="#constructing-confidence-intervals"><span class="header-section-number">3</span> Constructing confidence intervals</a>
  <ul class="collapse">
<li><a href="#confidence-intervals-for-regression-parameters" id="toc-confidence-intervals-for-regression-parameters" class="nav-link" data-scroll-target="#confidence-intervals-for-regression-parameters"><span class="header-section-number">3.1</span> Confidence Intervals for Regression Parameters</a></li>
  </ul>
</li>
  <li><a href="#inference-using-confidence-intervals" id="toc-inference-using-confidence-intervals" class="nav-link" data-scroll-target="#inference-using-confidence-intervals"><span class="header-section-number">4</span> Inference using Confidence Intervals</a></li>
  <li><a href="#variable-selection-using-confidence-intervals" id="toc-variable-selection-using-confidence-intervals" class="nav-link" data-scroll-target="#variable-selection-using-confidence-intervals"><span class="header-section-number">5</span> Variable selection using confidence intervals</a></li>
  <li><a href="#model-comparisons-using-objective-criteria" id="toc-model-comparisons-using-objective-criteria" class="nav-link" data-scroll-target="#model-comparisons-using-objective-criteria"><span class="header-section-number">6</span> Model comparisons using objective criteria</a></li>
  <li><a href="#a-final-word-on-model-selection" id="toc-a-final-word-on-model-selection" class="nav-link" data-scroll-target="#a-final-word-on-model-selection"><span class="header-section-number">7</span> A final word on model selection</a></li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="notes_24_25.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Week 3: Regression modelling part 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><style>
p.caption {
  font-size: 1.4em;
}
</style>
<section id="regression-modelling-with-one-numerical-and-one-categorical-explanatory-variable" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Regression modelling with one numerical and one categorical explanatory variable</h1>
<p>Let’s expand upon what we learned last week by revisiting the instructor evaluation data set <code>evals</code>. In Week 3 you were tasked with examining the relationship between teaching score (<code>score</code>) and age (<code>age</code>). Now, let’s also introduce the additional (binary) categorical explanatory variable gender (<code>gender</code>). That is, we we will be examining:</p>
<ul>
<li>the teaching score (<code>score</code>) as our outcome variable <span class="math inline">\(y\)</span>;</li>
<li>age (<code>age</code>) as our numerical explanatory variable <span class="math inline">\(x_1\)</span>; and</li>
<li>gender (<code>gender</code>) as our categorical explanatory variable <span class="math inline">\(x_2\)</span>.</li>
</ul>
<section id="exploratory-data-analysis" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">1.1</span> Exploratory data analysis</h2>
<p>Start by subsetting the <code>evals</code> data set so that we only have the variables we are interested in, that is, <code>score</code>, <code>age</code> and <code>gender</code>. Note, it is best to give your new data set a different name than evals as to not overwrite the original <code>evals</code> data set. Your new data set should look like the one below.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can also view your data set using the <code>glimpse</code> function, or by opening a spreadsheet view in RStudio using the <code>View</code> function.</p>
<p>Use the <code>skim</code> function to obtain some summary statistics from our data:</p>
<div class="webex-solution">
<button>
Answer
</button>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">eval.score</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">skim</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">eval.score</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">463</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 34%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">mal: 268, fem: 195</td>
</tr>
<tr class="even">
<td style="text-align: left;">ethnicity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">not: 399, min: 64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">language</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">eng: 435, non: 28</td>
</tr>
<tr class="even">
<td style="text-align: left;">rank</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">ten: 253, ten: 108, tea: 102</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pic_outfit</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">not: 386, for: 77</td>
</tr>
<tr class="even">
<td style="text-align: left;">pic_color</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">col: 385, bla: 78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cls_level</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">upp: 306, low: 157</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">232.00</td>
<td style="text-align: right;">133.80</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">116.50</td>
<td style="text-align: right;">232.00</td>
<td style="text-align: right;">347.5</td>
<td style="text-align: right;">463.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">prof_ID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45.15</td>
<td style="text-align: right;">27.55</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: right;">43.00</td>
<td style="text-align: right;">70.5</td>
<td style="text-align: right;">94.00</td>
<td style="text-align: left;">▇▇▆▆▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">score</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">4.30</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▅▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">48.37</td>
<td style="text-align: right;">9.80</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: right;">48.00</td>
<td style="text-align: right;">57.0</td>
<td style="text-align: right;">73.00</td>
<td style="text-align: left;">▅▆▇▆▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">8.17</td>
<td style="text-align: left;">▃▇▇▃▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">cls_did_eval</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">36.62</td>
<td style="text-align: right;">45.02</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: right;">380.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cls_students</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">55.18</td>
<td style="text-align: right;">75.07</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">60.0</td>
<td style="text-align: right;">581.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<p>Now, let’s compute the correlation coefficient between our outcome variable <code>score</code> and our numerical explanatory variable <code>age</code>:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">eval.score</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">get_correlation</span><span class="op">(</span>formula <span class="op">=</span> <span class="va">score</span> <span class="op">~</span> <span class="va">age</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     cor
   &lt;dbl&gt;
1 -0.107</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why do we not include the categorical variable <code>gender</code> when calculating the correlation?</p>
<div class="webex-solution">
<button>
Answer
</button>
<p>The correlation coefficient only exists between numerical variables, which is why we do not include our categorical variable <code>gender</code>.</p>
</div>
</div>
</div>
<p>We can now visualise our data by producing a scatterplot, where seeing as we have the categorical variable <code>gender</code>, we shall plot the points using different colours for each gender:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">eval.score</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">score</span>, color <span class="op">=</span> <span class="va">gender</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>, y <span class="op">=</span> <span class="st">"Teaching Score"</span>, color <span class="op">=</span> <span class="st">"Gender"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/evalsscat-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption> Instructor evaluation scores by age and gender. The points have been jittered.</figcaption></figure>
</div>
</div>
</div>
<p><strong>Note</strong>: The above code has jittered the points, however, this is not necessary and <code>geom_point</code> would suffice. To plot separate points by gender we simply add the <code>color</code> argument to the <code>aes</code> function and pass to it <code>gender</code>.</p>
<p>From the scatterplot we can see that:</p>
<ul>
<li>There are very few women over the age of 60 in our data set.</li>
<li>From the plotted regression lines we can see that the lines have different slopes for men and women. That is, the associated effect of increasing age appears to be more severe for women than it does for men, i.e.&nbsp;the teaching score of women drops faster with age.</li>
</ul></section><section id="multiple-regression-parallel-slopes-model" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="multiple-regression-parallel-slopes-model">
<span class="header-section-number">1.2</span> Multiple regression: parallel slopes model</h2>
<p>Here, we shall begin by fitting what is referred to as a parallel regression lines model. This model implies that the slope of relationship between teaching score (<code>score</code>) and age (<code>age</code>) is the same for both males and females, with only the intercept of the regression lines changing. Hence, our parallel regression lines model is given as:</p>
<p><span class="math display">\[\begin{align}
y_{i} &amp;= \alpha + \beta_1 x_{1i} + \beta_2 x_{2i} + \epsilon_i \nonumber \\
&amp;= \alpha + \beta_{\mbox{age}} \cdot \mbox{age} + \beta_{\mbox{male}} \cdot \mathbb{I}_{\mbox{male}}(x) + \epsilon_i, \nonumber
\end{align}\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\alpha\)</span> is the intercept of the regression line for females;</p></li>
<li><p><span class="math inline">\(\beta_{\mbox{age}}\)</span> is the slope of the regression line for both males and females;</p></li>
<li><p><span class="math inline">\(\beta_{\mbox{male}}\)</span> is the additional term added to <span class="math inline">\(\alpha\)</span> to get the intercept of the regression line for males; and</p></li>
<li>
<p><span class="math inline">\(\mathbb{I}_{\mbox{male}}(x)\)</span> is an indicator function such that</p>
<p><span class="math display">\[\mathbb{I}_{\mbox{male}}(x)=\left\{
            \begin{array}{ll}
              1 ~~~ \mbox{if gender} ~ x ~ \mbox{is male},\\
              0 ~~~ \mbox{Otherwise}.\\
            \end{array}
          \right.\]</span></p>
</li>
</ul>
<p>We can fit the parallel regression lines model as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_spec</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">set_engine</span><span class="op">(</span><span class="st">"lm"</span><span class="op">)</span></span>
<span><span class="va">par.model</span> <span class="op">&lt;-</span> <span class="va">lm_spec</span> <span class="op">|&gt;</span> <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">eval.score</span><span class="op">)</span></span>
<span><span class="va">par.model</span> <span class="op">&lt;-</span> <span class="va">par.model</span> <span class="op">|&gt;</span> <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">par.model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term         estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept       4.48      0.125     35.8    0        4.24     4.73 
2 age            -0.009     0.003     -3.28   0.001   -0.014   -0.003
3 gender: male    0.191     0.052      3.63   0        0.087    0.294</code></pre>
</div>
</div>
<p>Hence, the regression line for females is given by:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = 4.48 - 0.009 \cdot \mbox{age},\]</span></p>
<p>while the regression line for males is given by:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = 4.48 - 0.009 \cdot \mbox{age} + 0.191 = 4.671 - 0.009 \cdot \mbox{age}.\]</span> Now, let’s superimpose our parallel regression lines onto the scatterplot of teaching score against age:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">eval.score</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">score</span>, color <span class="op">=</span> <span class="va">gender</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>, y <span class="op">=</span> <span class="st">"Teaching Score"</span>, color <span class="op">=</span> <span class="st">"Gender"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_parallel_slopes</span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/parscat-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption> Instructor evaluation scores by age and gender with parallel regression lines superimposed.</figcaption></figure>
</div>
</div>
</div>
<p><strong>Note</strong>: go through the code used to create <code>coeff</code> and <code>slopes</code> and make sure you understand it.</p>
<p>From the parallel regression lines model both males and females have the same slope, that is, the associated effect of age on teaching score is the same for both men and women. Hence, for every one year increase in age, there is an associated decrease in teaching score of 0.009. However, male instructors have a higher intercept term, that is, there is a vertical bump in the regression line for males in teaching scores. This is linked to the average difference in teaching scores that males obtain relative to females.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is different between our previous scatterplot of teaching score against age (Figure 6) and the one we just created with our parallel lines superimposed (Figure 7)?</p>
<div class="webex-solution">
<button>
Answer
</button>
<p>In the original plot we have what is referred to as an interaction effect between age and gender. Hence, gender interacts in different ways for both males and females by age, and as such we should have different intercepts <strong>and</strong> slopes.</p>
</div>
</div>
</div>
</section><section id="multiple-regression-interaction-model" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="multiple-regression-interaction-model">
<span class="header-section-number">1.3</span> Multiple regression: interaction model</h2>
<p>There is an <em>interaction effect</em> if the associated effect of one variable depends on the value of another variable. For example, the effect of age here will depend on whether the instructor is male or female, that is, the effect of age on teaching scores will differ by gender. The interaction model can be written as:</p>
<p><span class="math display">\[\begin{align}
y_{i} &amp;= \alpha + \beta_1  x_{1i} + \beta_2  x_{2i} + \beta_3  x_{1i}  x_{2i} + \epsilon_i \nonumber \\
&amp;= \alpha + \beta_{\mbox{age}} \cdot \mbox{age} + \beta_{\mbox{male}} \cdot \mathbb{I}_{\mbox{male}}(x) + \beta_{\mbox{age, male}} \cdot \mbox{age} \cdot \mathbb{I}_{\mbox{male}}(x) + \epsilon_i, \nonumber
\end{align}\]</span></p>
<p>where <span class="math inline">\(\beta_{\mbox{age, male}} \cdot \mbox{age} \cdot \mathbb{I}_{\mbox{male}}(x)\)</span> corresponds to the interaction term.</p>
<p>In order to fit an interaction term within our regression model we replace the <code>+</code> sign with the <code>*</code> sign as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_spec</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="va">lm_spec</span> <span class="op">|&gt;</span> <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">*</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">eval.score</span><span class="op">)</span></span>
<span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="va">int.model</span> <span class="op">|&gt;</span> <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">int.model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term           estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept         4.88      0.205     23.8    0        4.48     5.29 
2 age              -0.018     0.004     -3.92   0       -0.026   -0.009
3 gender: male     -0.446     0.265     -1.68   0.094   -0.968    0.076
4 age:gendermale    0.014     0.006      2.45   0.015    0.003    0.024</code></pre>
</div>
</div>
<p>Hence, the regression line for females is given by:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = 4.88 - 0.018 \cdot \mbox{age},\]</span> while the regression line for males is given by:</p>
<p><span class="math display">\[\widehat{\mbox{score}} = 4.88 - 0.018 \cdot \mbox{age} - 0.446 + 0.014 \cdot \mbox{age} = 4.434 - 0.004 \cdot \mbox{age}.\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>How do they compare with the teaching score values from the parallel regression lines model?</p>
<div class="webex-solution">
<button>
Answer
</button>
<p>Here, we can see that, although the intercept for male instructors may be lower, the associated average decrease in teaching score with age (0.004) is not as severe as it is for female instructors (0.018).</p>
</div>
</div>
</div>
</section><section id="assessing-model-fit" class="level2" data-number="1.4"><h2 data-number="1.4" class="anchored" data-anchor-id="assessing-model-fit">
<span class="header-section-number">1.4</span> Assessing model fit</h2>
<p>Now we have to assess the fit of the model by looking at plots of the residuals. We shall do this for the interaction model. First, we need to obtain the fitted values and residuals from the interaction model as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">regression.points</span> <span class="op">&lt;-</span> <span class="fu">get_regression_points</span><span class="op">(</span><span class="va">int.model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 463 × 6
      ID score   age gender score_hat residual
   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;
 1     1   4.7    36 female      4.25    0.448
 2     2   4.1    36 female      4.25   -0.152
 3     3   3.9    36 female      4.25   -0.352
 4     4   4.8    36 female      4.25    0.548
 5     5   4.6    59 male        4.20    0.399
 6     6   4.3    59 male        4.20    0.099
 7     7   2.8    59 male        4.20   -1.40 
 8     8   4.1    51 male        4.23   -0.133
 9     9   3.4    51 male        4.23   -0.833
10    10   4.5    40 female      4.18    0.318
# ℹ 453 more rows</code></pre>
</div>
</div>
<p>Let’s start by looking at a scatterplot of the residuals against the explanatory variable by gender:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"age"</span>, y <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/intresid1-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Residuals vs the explanatory variable age by gender.</figcaption></figure>
</div>
</div>
</div>
<p>Now, we can plot the residuals against the fitted values:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">score_hat</span>, y <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Fitted values"</span>, y <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"blue"</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span> <span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/intresid2-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Residuals vs the fitted values.</figcaption></figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>Finally, let’s plot histograms of the residuals to assess whether they are normally distributed with mean zero:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">regression.points</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">residual</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">0.25</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Residual"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span><span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/intresid3-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Histograms of the residuals by gender.</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="sample-statistics" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Sample statistics</h1>
<p>This week, and in previous weeks, we have seen many examples of calculating <em>sample statistics</em> such as means, percentiles, standard deviations and regression coefficients. These <em>sample statistics</em> are used as <em>point estimates</em> of <em>population parameters</em> which describe the <em>population</em> from which the <em>sample</em> of data was taken. That last sentence assumes you’re familiar with concepts and terminology about sampling (e.g.&nbsp;from the <em>Statistical Inference</em> course in 1st Semester) so here is a summary of some key terms:</p>
<ol type="1">
<li><p><strong>Population</strong>: The population is a set of <span class="math inline">\(N\)</span> observations of interest.</p></li>
<li><p><strong>Population parameter</strong>: A population parameter is a numerical summary value about the population. In most settings, this is a value that’s unknown and you wish you knew it.</p></li>
<li>
<p><strong>Census</strong>: An exhaustive enumeration/counting of all observations in the population in order to compute the population parameter’s numerical value <em>exactly</em>.</p>
<ul>
<li>When <span class="math inline">\(N\)</span> is small, a census is feasible. However, when <span class="math inline">\(N\)</span> is large, a census can get very expensive, either in terms of time, energy, or money.</li>
</ul>
</li>
<li>
<p><strong>Sampling</strong>: Collecting a sample of size <span class="math inline">\(n\)</span> of observations from the population. Typically the sample size <span class="math inline">\(n\)</span> is much smaller than the population size <span class="math inline">\(N\)</span>, thereby making sampling a much cheaper procedure than a census.</p>
<ul>
<li>It is important to remember that the lowercase <span class="math inline">\(n\)</span> corresponds to the sample size and uppercase <span class="math inline">\(N\)</span> corresponds to the population size, thus <span class="math inline">\(n \leq N\)</span>.</li>
</ul>
</li>
<li><p><strong>Point estimates/sample statistics</strong>: A summary statistic based on the sample of size <span class="math inline">\(n\)</span> that <em>estimates</em> the unknown population parameter.</p></li>
<li><p><strong>Representative sampling</strong>: A sample is said be a <em>representative sample</em> if it “looks like the population”. In other words, the sample’s characteristics are a good representation of the population’s characteristics.</p></li>
<li><p><strong>Generalisability</strong>: We say a sample is <em>generalisable</em> if any results based on the sample can generalise to the population.</p></li>
<li><p><strong>Bias</strong>: In a statistical sense, we say <em>bias</em> occurs if certain observations in a population have a higher chance of being sampled than others. We say a sampling procedure is <em>unbiased</em> if every observation in a population had an equal chance of being sampled.</p></li>
<li><p><strong>Random sampling</strong>: We say a sampling procedure is <em>random</em> if we sample randomly from the population in an unbiased fashion.</p></li>
</ol>
<section id="inference-using-sample-statistics" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="inference-using-sample-statistics">
<span class="header-section-number">2.1</span> Inference using sample statistics</h2>
<p>The table below lists a variety of contexts where sample statistics can be used to estimate population parameters. In all 6 cases, the point estimate/sample statistic <em>estimates</em> the unknown population parameter. It does so by computing summary statistics based on a sample of size <span class="math inline">\(n\)</span>. We’ll cover Scenarios 5 and 6, namely construct CIs for the parameters in simple and multiple linear regression models. We will consider CIs based on theoretical results when standard assumptions hold, although sampling procedures such as bootstrap also exist. We will also consider how to use CIs for variable selection and finish by considering a model selection strategy based on objective measures for model comparisons.</p>
<!-- # ```{r inference-summary-table, echo=FALSE, message=FALSE, warning=FALSE, out.width = '10%'} -->
<!-- # # Original at https://docs.google.com/spreadsheets/d/1QkOpnBGqOXGyJjwqx1T2O5G5D72wWGfWlPyufOgtkk4/edit#gid=0 -->
<!-- # library(dplyr) -->
<!-- # library(readr) -->
<!-- # read_csv("data/ch9_summary_table - Sheet1.csv", na = "") |>  -->
<!-- #   kable( -->
<!-- #     caption = "Scenarios of sample statisitics for inference",  -->
<!-- #     booktabs = TRUE -->
<!-- #   ) -->
<!-- # ``` -->
<p>Table 1: Scenarios of sample statistics for inference.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: left;">Population Parameter</th>
<th style="text-align: left;">Population Notation</th>
<th style="text-align: left;">Sample Statistic</th>
<th style="text-align: left;">Sample Notation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Population proportion</td>
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">Sample proportion</td>
<td style="text-align: left;"><span class="math inline">\(\widehat{p}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Population mean</td>
<td style="text-align: left;"><span class="math inline">\(\mu\)</span></td>
<td style="text-align: left;">Sample mean</td>
<td style="text-align: left;"><span class="math inline">\(\bar{x}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Diff.in pop. props</td>
<td style="text-align: left;"><span class="math inline">\(p_1 - p_2\)</span></td>
<td style="text-align: left;">Diff. in sample props</td>
<td style="text-align: left;"><span class="math inline">\(\widehat{p}_1 - \widehat{p}_2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Diff. in pop. means</td>
<td style="text-align: left;"><span class="math inline">\(\mu_1 - \mu_2\)</span></td>
<td style="text-align: left;">Diff. in sample means</td>
<td style="text-align: left;"><span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Pop. intercept</td>
<td style="text-align: left;"><span class="math inline">\(\beta_0\)</span></td>
<td style="text-align: left;">Sample intercept</td>
<td style="text-align: left;">
<span class="math inline">\(\widehat{\beta}_0\)</span> or <span class="math inline">\(b_0\)</span>
</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Pop. slope</td>
<td style="text-align: left;"><span class="math inline">\(\beta_1\)</span></td>
<td style="text-align: left;">Sample slope</td>
<td style="text-align: left;">
<span class="math inline">\(\widehat{\beta}_1\)</span> or <span class="math inline">\(b_1\)</span>
</td>
</tr>
</tbody>
</table>
<p>In reality, we don’t have access to the population parameter values (if we did, why would we need to estimate them?) we only have a single sample of data from a larger population. We’d like to be able to make some reasonable guesses about population parameters using that single sample to create a range of plausible values for a population parameter. This range of plausible values is known as a <strong>confidence interval</strong>.</p>
<p>There are theoretical ways of defining confidence intervals for these different scenarios (such as you saw in ‘Statistical Inference’ in Semester 1). But we can also use a single sample to get some idea of how other samples might vary in terms of their sample statistics, i.e.&nbsp;to estimate the sampling distributions of sample statistics. One common way this is done is via a process known as bootstrapping.</p>
<p>The confidence intervals we will see this week are calculated using the theoretical results based on the standard assumptions that you will have seen in <em>Regression Modelling</em> in first semester. These values are <strong>not</strong> based on bootstrapping techniques since these become much harder to implement when working with multiple variables and its beyond the scope of this course.</p>
</section></section><section id="constructing-confidence-intervals" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Constructing confidence intervals</h1>
<p>A <strong>confidence interval</strong> gives a range of plausible values for a population parameter. It depends on a specified <em>confidence level</em> with higher confidence levels corresponding to wider confidence intervals and lower confidence levels corresponding to narrower confidence intervals. Common confidence levels include 90%, 95%, and 99%.</p>
<p><strong>Confidence intervals</strong> are simple to define and play an important role in the sciences and any field that uses data. You can think of a confidence interval as playing the role of a net when fishing. Instead of just trying to catch a fish with a single spear (estimating an unknown parameter by using a single point estimate/sample statistic), we can use a net to try to provide a range of possible locations for the fish (use a range of possible values based around our sample statistic to make a plausible guess as to the location of the parameter).</p>
<section id="confidence-intervals-for-regression-parameters" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="confidence-intervals-for-regression-parameters">
<span class="header-section-number">3.1</span> Confidence Intervals for Regression Parameters</h2>
<p>To illustrate this, let’s have another look at teaching evaluations data <code>evals</code> in the <code>moderndive</code> package that we used in Week 3 and start with the SLR model with <code>age</code> as the the single explanatory variable and the instructors’ evaluation <code>score</code>s as the response variable. This data and the fitted model are shown here.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slr.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">slr.model</span> <span class="op">&lt;-</span> <span class="va">slr.model</span> <span class="op">|&gt;</span> <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">evals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> (Intercept)          age 
 4.461932354 -0.005938225 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/modelslr-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Figure 1: SLR model applied to the teaching evaluation Data.</figcaption></figure>
</div>
</div>
</div>
<p>The point estimate of the slope parameter here is <span class="math inline">\(\widehat{\beta}=\)</span> -0.006.</p>
<p>Let’s continue with the teaching evaluations data by fitting the multiple regression model with one numerical and one categorical explanatory variable. In this model:</p>
<ul>
<li>
<span class="math inline">\(y\)</span>: response variable of instructor evaluation <code>score</code>
</li>
<li>explanatory variables
<ul>
<li>
<span class="math inline">\(x_1\)</span>: numerical explanatory variable of <code>age</code>
</li>
<li>
<span class="math inline">\(x_2\)</span>: categorical explanatory variable of <code>gender</code>
</li>
</ul>
</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">evals_multiple</span> <span class="op">&lt;-</span> <span class="va">evals</span> <span class="op">|&gt;</span></span>
<span>                  <span class="fu">select</span><span class="op">(</span><span class="va">score</span>, <span class="va">gender</span>, <span class="va">age</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>First, recall that we had two competing potential models to explain professors’ teaching evaluation scores:</p>
<ol type="1">
<li>Model 1: Parallel lines model (no interaction term) - both male and female professors have the same slope describing the associated effect of age on teaching score</li>
<li>Model 2: Interaction model - allowing for male and female professors to have different slopes describing the associated effect of age on teaching score</li>
</ol>
<p><strong>Refresher: Visualisations</strong></p>
<p>Recall the plots we made for both these models:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/model1-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Model 1: Parallel regression lines.</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="notes_24_25_files/figure-html/model2-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Model 2: Separate regression lines.</figcaption></figure>
</div>
</div>
</div>
<p><strong>Refresher: Regression tables</strong></p>
<p>Let’s also recall the regression models. First, the regression model with no interaction effect: note the use of <code>+</code> in the formula.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">par.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">par.model</span> <span class="op">&lt;-</span> <span class="va">par.model</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">evals_multiple</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">par.model</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span></span>
<span>               digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>               caption <span class="op">=</span> <span class="st">"Model 1: Regression model with no interaction effect included."</span>, </span>
<span>               booktabs <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>        <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model 1: Regression model with no interaction effect included.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std_error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">lower_ci</th>
<th style="text-align: right;">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">4.484</td>
<td style="text-align: right;">0.125</td>
<td style="text-align: right;">35.792</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">4.238</td>
<td style="text-align: right;">4.730</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.009</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-3.280</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">-0.014</td>
<td style="text-align: right;">-0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender: male</td>
<td style="text-align: right;">0.191</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">3.632</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">0.294</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Second, the regression model with an interaction effect: note the use of <code>*</code> in the formula.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="va">int.model</span>  <span class="op">|&gt;</span></span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">*</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">evals_multiple</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">int.model</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span></span>
<span>                digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>                caption <span class="op">=</span> <span class="st">"Model 2: Regression model with interaction effect included."</span>, </span>
<span>                booktabs <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>      <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model 2: Regression model with interaction effect included.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std_error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">lower_ci</th>
<th style="text-align: right;">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">4.883</td>
<td style="text-align: right;">0.205</td>
<td style="text-align: right;">23.795</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">4.480</td>
<td style="text-align: right;">5.286</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.018</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-3.919</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">-0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender: male</td>
<td style="text-align: right;">-0.446</td>
<td style="text-align: right;">0.265</td>
<td style="text-align: right;">-1.681</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">-0.968</td>
<td style="text-align: right;">0.076</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:gendermale</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">2.446</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.024</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice that, together with the estimated parameter values, the tables include other information about each estimated parameter in the model, namely:</p>
<ul>
<li>
<strong>std_error</strong>: the standard error of each parameter estimate;</li>
<li>
<strong>statistic</strong>: the test statistic value used to test the null hypothesis that the population parameter is zero;</li>
<li>
<strong>p_value</strong>: the <span class="math inline">\(p\)</span> value associated with the test statistic under the null hypothesis; and</li>
<li>
<strong>lower_ci</strong> and <strong>upper_ci</strong>: the lower and upper bounds of the 95% confidence interval for the population parameter</li>
</ul>
<p>These values are calculated using the theoretical results based on the standard assumptions that you will have seen in <em>Regression Modelling</em> in first semester. Theses values are <strong>not</strong> based on bootstrapping techniques but theoretical results since these become much harder to implement when working with multiple variables and its beyond the scope of this course.</p>
</section></section><section id="inference-using-confidence-intervals" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Inference using Confidence Intervals</h1>
<p>Having described several ways of calculating confidence intervals for model parameters, we are now in a position to interpret them for the purposes of statistical inference.</p>
<p><strong>Simple Linear Regression:</strong> <span class="math inline">\(\widehat{y}_i = \alpha + \beta x_i\)</span></p>
<p>Whether we have obtained a confidence interval for <span class="math inline">\(\beta\)</span> in a simple linear regression model via bootstrapping or theoretical results based on assumptions, the interpretation of the interval is the same. As we saw in Week 7,</p>
<blockquote class="blockquote">
<p>A confidence interval gives a range of plausible values for a population parameter.</p>
</blockquote>
<p>We can therefore use the confidence interval for <span class="math inline">\(\beta\)</span> to state a range of plausible values and, just as usefully, what values are <strong>not</strong> plausible. The most common value to compare the confidence interval of <span class="math inline">\(\beta\)</span> with is 0 (zero), since <span class="math inline">\(\beta = 0\)</span> says there is <em>no</em> (linear) relationship between the response variable (<span class="math inline">\(y\)</span>) and the explanatory variable (<span class="math inline">\(x\)</span>). Therefore, if 0 lies within the confidence interval for <span class="math inline">\(\beta\)</span> then there is insufficient evidence of a linear relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>. However, if 0 <strong>does not</strong> lie within the confidence interval, then we conclude that <span class="math inline">\(\beta\)</span> is significantly different from zero and therefore that there is evidence of a linear relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>.</p>
<p>Let’s use the confidence interval based on theoretical results for the slope parameter in the SLR model applied to the teacher evaluation scores with <code>age</code> as the the single explanatory variable and the instructors’ evaluation <code>score</code>s as the outcome variable.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">slr.model</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>          <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span></span>
<span>          digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>          caption <span class="op">=</span> <span class="st">"Estimates from the SLR model of `score` on `age`."</span>, </span>
<span>          booktabs <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>          <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estimates from the SLR model of <code>score</code> on <code>age</code>.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std_error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">lower_ci</th>
<th style="text-align: right;">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">4.462</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">35.195</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">4.213</td>
<td style="text-align: right;">4.711</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-2.311</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">-0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Multiple Regression</strong></p>
<p>Consider, again, the fitted interaction model for <code>score</code> with <code>age</code> and <code>gender</code> as the two explanatory variables.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">int.model</span> <span class="op">&lt;-</span> <span class="va">int.model</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">*</span> <span class="va">gender</span>, data <span class="op">=</span> <span class="va">evals_multiple</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">get_regression_table</span><span class="op">(</span><span class="va">int.model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model 2: Regression model with interaction effect included.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std_error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">lower_ci</th>
<th style="text-align: right;">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">4.883</td>
<td style="text-align: right;">0.205</td>
<td style="text-align: right;">23.795</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">4.480</td>
<td style="text-align: right;">5.286</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.018</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-3.919</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">-0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender: male</td>
<td style="text-align: right;">-0.446</td>
<td style="text-align: right;">0.265</td>
<td style="text-align: right;">-1.681</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">-0.968</td>
<td style="text-align: right;">0.076</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:gendermale</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">2.446</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.024</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="variable-selection-using-confidence-intervals" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Variable selection using confidence intervals</h1>
<p>When there is more than one explanatory variable in a model, the parameter associated with each explanatory variable is interpreted as the change in the mean response based on a 1-unit change in the corresponding explanatory variable <strong>keeping all other variables held constant</strong>. Therefore, care must be taken when interpreting the confidence intervals of each parameter by acknowledging that each are plausible values <strong>conditional on all the other explanatory variables in the model</strong>.</p>
<p>Because of the interdependence between the parameter estimates and the variables included in the model, choosing which variables to include in the model is a rather complex task. We will introduce some of the ideas in the simple case where we have 2 potential explanatory variables (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>) and use confidence intervals to decide which variables will be useful in predicting the response variable (<span class="math inline">\(y\)</span>).</p>
<p>One approach is to consider a hierarchy of models:</p>
<p><span class="math display">\[y_i = \alpha + \beta_1 x_{1i} + \beta_2 x_{2i}\]</span><br><span class="math display">\[y_i = \alpha + \beta_1 x_{1i} \qquad \qquad \qquad y_i = \alpha + \beta_2 x_{2i}\]</span><br><span class="math display">\[y_i = \alpha\]</span></p>
<!-- \begin{displaymath} -->
<!-- \hspace{-0.4cm} -->
<!--     \xymatrix{ -->
<!--         & \mathbb{E}(Y | x_1, x_2) = \alpha + \beta x_1 + \gamma x_2 \ar@/_/[dl] \ar@/^/[dr]  \\ -->
<!--         \mathbb{E}(Y | x_1, x_2) = \alpha + \beta x_1 \ar@/_/[dr] &        & \mathbb{E}(Y | x_1, x_2) = \alpha + \gamma x_2 \ar@/^/[dl] \\ -->
<!--         & \mathbb{E}(Y | x_1, x_2) = \alpha & } -->
<!-- \end{displaymath} -->
<p>Within this structure we might take a top-down approach:</p>
<ol type="1">
<li>Fit the most general model, i.e.&nbsp;<span class="math inline">\(y_i = \alpha + \beta_1 x_{1i} + \beta_2 x_{2i}\)</span> since we believe this is likely to provide a good description of the data</li>
<li>Construct confidence intervals for <span class="math inline">\(\beta_1 ~\textrm{and} ~\beta_2\)</span>
<ol type="a">
<li>If both intervals exclude 0 then retain the model with both <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>.</li>
<li>If the interval for <span class="math inline">\(\beta_1\)</span> contains 0 but that for <span class="math inline">\(\beta_2\)</span> does not, fit the model with <span class="math inline">\(x_2\)</span> alone.</li>
<li>If the interval for <span class="math inline">\(\beta_2\)</span> contains 0 but that for <span class="math inline">\(\beta_1\)</span> does not, fit the model with <span class="math inline">\(x_1\)</span> alone.</li>
<li>If both intervals include 0 it may still be that a model with one variable is useful. In this case the two models with the single variables should be fitted and intervals for <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> constructed and compared with 0.</li>
</ol>
</li>
</ol>
<p>If we have only a few explanatory variables, then an extension of the strategy outlined above would be effective, i.e.&nbsp;start with the full model and simplify by removing terms until no further terms can be removed. When the number of explanatory variables is large the problem becomes more difficult. We will consider this more challenging situation in the next section.</p>
<p>Recall that as well as <code>age</code> and <code>gender</code>, there is also a potential explanatory variable <code>bty_avg</code> in the <code>evals</code> data, i.e.&nbsp;the numerical variable of the average beauty score from a panel of six students’ scores between 1 and 10. We can fit the multiple regression model with the two continuous explanatory variables <code>age</code> and <code>bty_avg</code> as follows:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr.model</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">mlr.model</span> <span class="op">&lt;-</span> <span class="va">mlr.model</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">fit</span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">bty_avg</span>, data <span class="op">=</span> <span class="va">evals</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">extract_fit_engine</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estimates from the MLR model with <code>age</code> and <code>bty_avg</code>.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std_error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">lower_ci</th>
<th style="text-align: right;">upper_ci</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">4.055</td>
<td style="text-align: right;">0.170</td>
<td style="text-align: right;">23.870</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">3.721</td>
<td style="text-align: right;">4.389</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-1.148</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">-0.008</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0.061</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">3.548</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.094</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="model-comparisons-using-objective-criteria" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Model comparisons using objective criteria</h1>
<p>As was noted in the last section, when the number of potential explanatory variables is large the problem of selecting which variables to include in the final model becomes more difficult. The selection of a final regression model always involves a compromise:</p>
<ul>
<li>Predictive accuracy (improved by including more predictor/explanatory variables)</li>
<li>Interpretability (achieved by having less predictor/explanatory variables)</li>
</ul>
<p>There are many objective criteria for comparing different models applied to the same data set. All of them trade off the two objectives above, i.e.&nbsp;fit to the data against complexity. Common examples include:</p>
<ol type="1">
<li>The <span class="math inline">\(R^2_{adj}\)</span> values, i.e.&nbsp;the proportion of the total variation of the response variable explained by the models.</li>
</ol>
<p><span class="math display">\[R_{adj}^2 = 1 - \frac{RSS/(n-p-1)}{SST/(n-1)} = 100 \times \Bigg[ 1-\frac{\sum_{i=1}^n(y_i-\widehat{y}_i)^2/(n-p-1)}{\sum_{i=1}^n(y_i-\bar y_i)^2/(n-1)}\Bigg]\]</span></p>
<ul>
<li>where
<ul>
<li>
<span class="math inline">\(n\)</span> is the sample size</li>
<li>
<span class="math inline">\(p\)</span> is the number of parameters in the model</li>
<li>
<span class="math inline">\(RSS\)</span> is the residual sum of squares from the fitted model</li>
<li>
<span class="math inline">\(SST\)</span> is the total sum of squares around the mean response.</li>
</ul>
</li>
<li>
<span class="math inline">\(R_{adj}^2\)</span> values are used for nested models, i.e.&nbsp;where one model is a particular case of the other</li>
</ul>
<ol start="2" type="1">
<li>Akaike’s Information Criteria (AIC)</li>
</ol>
<p><span class="math display">\[AIC = -2 \cdot \mbox{log-likeihood} + 2p = n\ln\left(\frac{RSS}{n}\right)+2p\]</span></p>
<ul>
<li>A value based on the maximum likelihood function of the parameters in the fitted model penalised by the number of parameters in the model</li>
<li>It be used to compare any models fitted to the same response variable</li>
<li>The smaller the AIC the ‘better’ the model, i.e.&nbsp;no distributional results are employed to assess differences</li>
<li>See the <code>stepAIC</code> function from the <code>MASS</code> library that was mention in Week 6.</li>
</ul>
<ol start="3" type="1">
<li>Bayesian Information Criteria</li>
</ol>
<p><span class="math display">\[BIC = -2 \cdot \mbox{log-likeihood} +\ln(n)p\]</span></p>
<p>A popular data analysis strategy that can be adopted is to calculate <span class="math inline">\(R_{adj}^2\)</span>, <span class="math inline">\(AIC\)</span> and <span class="math inline">\(BIC\)</span> and compare the models which <strong>minimise</strong> the <span class="math inline">\(AIC\)</span> and <span class="math inline">\(BIC\)</span> with the model that <strong>maximises</strong> the <span class="math inline">\(R_{adj}^2\)</span>.</p>
<p>To illustrate this, let’s return to the <code>evals</code> data and the MLR on the teaching evaluation score <code>score</code> with the two continuous explanatory variables <code>age</code> and <code>bty_avg</code> and compare this with the SLR model with just <code>bty_avg</code>. To access these measures for model comparisons we can use the <code>glance</code> function in the <code>broom</code> package (not to be confused with the <code>glimpse</code> function from the <code>dplyr</code> package). Here, for the sake of simplicity, we simply use the <code>lm</code> function.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.comp.values.slr.age</span> <span class="op">&lt;-</span> <span class="fu">glance</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">evals</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0115       0.00931 0.541      5.34  0.0213     1  -372.  750.  762.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.comp.values.slr.bty_avg</span> <span class="op">&lt;-</span> <span class="fu">glance</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">bty_avg</span>, data <span class="op">=</span> <span class="va">evals</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0350        0.0329 0.535      16.7 0.0000508     1  -366.  738.  751.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.comp.values.mlr</span> <span class="op">&lt;-</span> <span class="fu">glance</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">bty_avg</span>, data <span class="op">=</span> <span class="va">evals</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    0.0378        0.0336 0.535      9.03 0.000142     2  -366.  739.  756.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>Note that <span class="math inline">\(R_{adj}^2\)</span>, <span class="math inline">\(AIC\)</span> and <span class="math inline">\(BIC\)</span> are contained in columns 2, 9 and 10 respectively. To access just these values and combine them in a single table we use:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'SLR(age)'</span>,<span class="st">'SLR(bty_avg)'</span>,<span class="st">'MLR'</span><span class="op">)</span> </span>
<span><span class="fu">bind_rows</span><span class="op">(</span><span class="va">model.comp.values.slr.age</span>, <span class="va">model.comp.values.slr.bty_avg</span>, </span>
<span>          <span class="va">model.comp.values.mlr</span>, .id <span class="op">=</span> <span class="st">"Model"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>          <span class="fu">select</span><span class="op">(</span><span class="va">Model</span>, <span class="va">adj.r.squared</span>, <span class="va">AIC</span>, <span class="va">BIC</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>          <span class="fu">mutate</span><span class="op">(</span>Model <span class="op">=</span> <span class="va">Models</span><span class="op">)</span> <span class="op">|&gt;</span>  </span>
<span>          <span class="fu">kable</span><span class="op">(</span></span>
<span>                digits <span class="op">=</span> <span class="fl">2</span>,</span>
<span>                caption <span class="op">=</span> <span class="st">"Model comparison values for different models."</span>, </span>
<span>          <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model comparison values for different models.</caption>
<thead><tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SLR(age)</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">749.62</td>
<td style="text-align: right;">762.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLR(bty_avg)</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">738.44</td>
<td style="text-align: right;">750.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MLR</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">739.12</td>
<td style="text-align: right;">755.67</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="a-final-word-on-model-selection" class="level1" data-number="7"><h1 data-number="7">
<span class="header-section-number">7</span> A final word on model selection</h1>
<p>A great deal of care should be taken in selecting predictor/explanatory variables for a model because the values of the regression coefficients depend upon the variables included in the model. Therefore, the predictors included and the order in which they are entered into the model can have great impact. In an ideal world, predictors should be selected based on past research and new predictors should be added to existing models based on the theoretical importance of the variables. One thing not to do is select hundreds of random predictors, bung them all into a regression analysis and hope for the best.</p>
<p>But in practice there are automatic strategies, such as <strong>Stepwise</strong> (see Week 6 on stepwise regression using <strong>AIC</strong>) and <strong>Best Subsets</strong> regression, based on systematically searching through the entire list of variables not in the current model to make decisions on whether each should be included. These strategies need to be handled with care, and a proper discussion of them is beyond this course. Our best strategy is a mixture of judgement on what variables should be included as potential explanatory variables, together with an interval estimation and hypothesis testing strategy for assessing these. The judgement should be made in the light of advice from the problem context.</p>
<hr>
<p><strong>Golden rule for modelling</strong></p>
<blockquote class="blockquote">
<p>The key to modelling data is to only use the objective measures as a rough guide. In the end the choice of model will involve your own judgement. You have to be able to defend why you chose a particular model.</p>
</blockquote>


</section></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>