<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Data Analysis Week 8 - Week 8: Generalised Linear Models part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./UofG_Coat_of_Arms.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/bootstrap-icons-1.11.1/all.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="include/webex.css">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./UofG.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Data Analysis Week 8</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Week 8: Extra material</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li>
<a href="#logistic-regression-with-grouped-binary-data" id="toc-logistic-regression-with-grouped-binary-data" class="nav-link" data-scroll-target="#logistic-regression-with-grouped-binary-data"><span class="header-section-number">2</span> Logistic regression with grouped binary data</a>
  <ul class="collapse">
<li><a href="#modelling-grouped-binary-data-with-a-categorical-covariate" id="toc-modelling-grouped-binary-data-with-a-categorical-covariate" class="nav-link" data-scroll-target="#modelling-grouped-binary-data-with-a-categorical-covariate"><span class="header-section-number">2.1</span> Modelling grouped binary data with a categorical covariate</a></li>
  </ul>
</li>
  <li>
<a href="#models-for-multiple-categorical-responses" id="toc-models-for-multiple-categorical-responses" class="nav-link" data-scroll-target="#models-for-multiple-categorical-responses"><span class="header-section-number">3</span> Models for multiple categorical responses</a>
  <ul class="collapse">
<li><a href="#nominal-logistic-regression" id="toc-nominal-logistic-regression" class="nav-link" data-scroll-target="#nominal-logistic-regression"><span class="header-section-number">3.1</span> Nominal logistic regression</a></li>
  <li><a href="#parameter-estimation-and-fitted-values" id="toc-parameter-estimation-and-fitted-values" class="nav-link" data-scroll-target="#parameter-estimation-and-fitted-values"><span class="header-section-number">3.2</span> Parameter estimation and fitted values</a></li>
  <li><a href="#example-fitting-a-nominal-logistic-regression-in-r" id="toc-example-fitting-a-nominal-logistic-regression-in-r" class="nav-link" data-scroll-target="#example-fitting-a-nominal-logistic-regression-in-r"><span class="header-section-number">3.3</span> Example: Fitting a nominal logistic regression in R</a></li>
  <li><a href="#model-checking-and-model-comparisons" id="toc-model-checking-and-model-comparisons" class="nav-link" data-scroll-target="#model-checking-and-model-comparisons"><span class="header-section-number">3.4</span> Model checking and model comparisons</a></li>
  </ul>
</li>
  </ul><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Week 8: Generalised Linear Models part 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>Last week we introduced <strong>Generalised Linear Models</strong> (GLMs). Particularly, we looked at <strong>logistic regression</strong> to model outcomes of interest that take one of two categorical values (e.g.yes/no, success/failure, alive/dead). This week we will continue reviewing logistic regression to model grouped binary outcomes (e.g.&nbsp;number of successes out of a fixed number of trials) and then we we will generalise this to situations where the response variable is categorical with more than two categories. First lets look at the framework for modelling categorical data with only two categories, i.e.</p>
<ul>
<li><p><strong>binary</strong>, taking the value 1 (say success, with probability <span class="math inline">\(p\)</span>) or 0 (failure, with probability <span class="math inline">\(1-p\)</span>) or</p></li>
<li><p><strong>binomial</strong>, where <span class="math inline">\(y_i\)</span> is the number of events (successes) in a given number of trials <span class="math inline">\(n_i\)</span>, with the probability of success being <span class="math inline">\(p_i\)</span> and the probability of failure being <span class="math inline">\(1-p_i\)</span>.</p></li>
</ul>
<p>In both cases the distribution of <span class="math inline">\(y_i\)</span> is assumed to be binomial, but in the first case it is <span class="math inline">\(\mathrm{Bin}(1,p_i)\)</span> and in the second case it is <span class="math inline">\(\mathrm{Bin}(n_i,p_i)\)</span>. The first case was covered last week, so now lets focus on the second case.</p>
<p>Before we proceed, we will load all the packages needed for this week:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://moderndive.github.io/moderndive/">moderndive</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/performance/">performance</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/julianfaraway/faraway">faraway</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="logistic-regression-with-grouped-binary-data" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Logistic regression with grouped binary data</h1>
<p>Suppose that our binary outcome <span class="math inline">\(y_i\)</span> is grouped across <span class="math inline">\(n_i\)</span> number of trials, e.g.&nbsp;number of times a head landed when a coin was tossed on multiple occasions or the proportion of beetles that were killed after being exposed to an insecticide.</p>
<p>In such cases <span class="math inline">\(y_i \sim \mathrm{Bin}(n_i,p_i)\)</span>, often referred to as proportional data, since our dependent variables are expressed as percentages or fractions of a whole. Lets look at a an example.</p>
<p>It is known that the incubation temperature can affect the sex determination of turtles. An experiment was conducted where turtle eggs were incubated at various temperatures and the number of male and female hatchlings was recorded. The goal of the experiment was to examine the link between incubation temperature and the chance of hatchling being a male.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="turtles.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="473"></p>
</figure>
</div>
<p>The <code>turtle</code> data set within the <code>faraway</code> library contains the number of hatched male and female turtles across different temperatures, with 3 independent replicates for each temperature.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">turtles</span> <span class="op">=</span> <span class="fu">faraway</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/faraway/man/turtle.html">turtle</a></span> </span>
<span><span class="va">turtles</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">glimpse</span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15
Columns: 3
$ temp   &lt;dbl&gt; 27.2, 27.2, 27.2, 27.7, 27.7, 27.7, 28.3, 28.3, 28.3, 28.4, 28.…
$ male   &lt;int&gt; 1, 0, 1, 7, 4, 6, 13, 6, 7, 7, 5, 7, 10, 8, 9
$ female &lt;int&gt; 9, 8, 8, 3, 2, 2, 0, 3, 1, 3, 3, 2, 1, 0, 0</code></pre>
</div>
</div>
<p>Lets investigate whether the probability of a male being hatched increases or decrease with the temperature. First, we need to compute the proportion of males that hatched on each replicate per temperature. To do this, we obtain the ratio between the total number of male hatchlings and total number hatchlings (males+females):</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">turtles</span> <span class="op">=</span> <span class="va">turtles</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>totals <span class="op">=</span> <span class="va">male</span><span class="op">+</span><span class="va">female</span>,</span>
<span>         male_props <span class="op">=</span> <span class="va">male</span><span class="op">/</span><span class="va">totals</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see on the next plot, that the proportion of males hatchlings seems to increase as the incubation temperature rises.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">turtles</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y<span class="op">=</span> <span class="va">male_props</span>,x<span class="op">=</span><span class="va">temp</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y<span class="op">=</span><span class="st">"proportion of male hatchlings"</span>,x <span class="op">=</span> <span class="st">"temperature"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>To corroborate this result, we can fit a logistic regression to the data.</p>
<span class="math display">\[\begin{align}
y_i &amp;\sim \mathrm{Binomial}(n_i,p_i)\\
\mathrm{logit}(p_i) &amp;= \beta_0 +\beta_1 \times \mathrm{temperature}.
\end{align}\]</span>
<p>Here, <span class="math inline">\(y_i\)</span> denotes the number of hatched males on the <span class="math inline">\(i\)</span>th experiment replicate, <span class="math inline">\(n_i\)</span> is the fixed total number of hatched eggs per replicate, <span class="math inline">\(p_i\)</span> is the probability of a male turtle being hatched, and <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are our unknown parameters to be estimated.</p>
<p>Proportions can be modelled by providing an <span class="math inline">\(N \times 2\)</span> matrix of the number of positive events (num. of males hatchlings) and the number of negative events (number of female hatchlings):</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_turtles</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">male</span>,<span class="va">female</span><span class="op">)</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">turtles</span>,</span>
<span>                     family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>or by providing the proportion of males hatchlings and <code>weights</code> totals, i.e the number of trials (number of eggs in each replicate), in the <code>glm</code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_turtles</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">male_props</span> <span class="op">~</span> <span class="va">temp</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">turtles</span>,</span>
<span>                     weights <span class="op">=</span>  <span class="va">totals</span>,</span>
<span>                     family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These two formulations are valid and will yield to the same following result:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_turtles</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-61.32</td>
<td style="text-align: right;">12.02</td>
<td style="text-align: right;">-5.10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-86.83</td>
<td style="text-align: right;">-39.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">temp</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">5.13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">3.13</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The interpretation goes as follows:</p>
<ul>
<li><p>For every unit increase (celsius degrees presumably) in <em>Temperature,</em> the log-odds of a male being hatched increase by 2.21 i.e.&nbsp;the chances of hatching a male increases as the incubation temperature increases.</p></li>
<li><p>Given <span class="math inline">\(p_{val} &lt; 0.05\)</span>, we can <strong>reject the null hypothesis</strong> <span class="math inline">\(\beta_1 = 0\)</span> that one unit increase in temperature does not affect chances of a male being hatched.</p></li>
<li><p>For every unit increase in <em>Temperature</em>, the <strong>odds</strong> of hatching a male are <span class="math inline">\(\mathrm{exp}(\beta_1) = 9.13\)</span> times the odds of those with one <em>temperature</em> unit less.</p></li>
</ul>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>If an egg is incubated at a temperature of 27.5 degrees, what at the chances (odds) of a <strong>female</strong> being hatched.</p>
<div class="webex-solution">
<button>
I need a hint
</button>
<p>Recall that <span class="math inline">\(log~Odds ~ (male) = \mathrm{log}\left(\dfrac{P(male)}{1-P(male)}\right) = \hat{\beta_0} +\hat{\beta_1} \times temperature\)</span>, but we are interested in <span class="math inline">\(\dfrac{P(female)}{1-P(female)}\)</span>, thus <span class="math inline">\(Odds ~ (female) = \mathrm{exp}\left[- \mathrm{log}\left(\dfrac{P(male)}{1-P(male)} \right)\right] = \mathrm{exp}\left(-\left[\hat{\beta_0} +\hat{\beta_1} \times 27.5\right]\right)\)</span>.</p>
</div>
<div id="radio_MLZCIAFTJH" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_MLZCIAFTJH" value=""><span>The chances of an male being hatched are 45% greater than a female hatchling if the egg was incubated at a temperature of 27.5 degrees</span></label><label><input type="radio" autocomplete="off" name="radio_MLZCIAFTJH" value=""><span>The chances of an female being hatched are 45% greater than a male hatchling if the egg was incubated at a temperature of 27.5 degrees</span></label><label><input type="radio" autocomplete="off" name="radio_MLZCIAFTJH" value="answer"><span>The chances of an female being hatched are 67% greater than a male hatchling if the egg was incubated at a temperature of 27.5 degrees</span></label><label><input type="radio" autocomplete="off" name="radio_MLZCIAFTJH" value=""><span>The chances of an male being hatched are 67 greater than a female hatchling if the egg was incubated at a temperature of 27.5 degrees</span></label>
</div>
</div>
</div>
<p>We can now plot the predicted probabilities of a hatchling being male. However, notice that the number of unique temperature values in the <code>turtles</code> data set is not very large:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span> <span class="va">turtles</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">select</span><span class="op">(</span><span class="va">temp</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   temp
1  27.2
4  27.7
7  28.3
10 28.4
13 29.9</code></pre>
</div>
</div>
<p>Thus, we can create a coarser grid of temperature values to make our predictions and then use the <code><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model()</a></code> function as follows:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">temp_pred</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">27</span>,<span class="fl">30</span>,by<span class="op">=</span><span class="fl">0.01</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span><span class="va">model_turtles</span>, </span>
<span>           type <span class="op">=</span> <span class="st">"eff"</span>, </span>
<span>           title <span class="op">=</span> <span class="st">""</span>, </span>
<span>           terms<span class="op">=</span><span class="st">"temp[temp_pred]"</span>, </span>
<span>           axis.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Temperature"</span>, <span class="st">"Prob. of a hatchling being male"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-question-octagon " style="color: #6dc83c;" role="img" aria-hidden="true"></i> Question
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the probability of a turtle egg that is incubated in a temperature of 28.5 degrees to become a male?</p>
<div class="webex-solution">
<button>
I need a hint
</button>
<p>Recall that <span class="math inline">\(P~ (male) = \dfrac{Odds(male)}{1 + Odds(male)} = \dfrac{\mathrm{exp}(\hat{\beta_0} +\hat{\beta_1} \times temperature)}{1 + \mathrm{exp}(\hat{\beta_0} +\hat{\beta_1} \times temperature)}\)</span>. In R, the inverse logit transformation can be achieved using the <code><a href="https://rdrr.io/r/stats/Logistic.html">plogis()</a></code> function.</p>
</div>
<p><select class="webex-select"><option value="blank"></option>
<option value="">0.45</option>
<option value="">0.18</option>
<option value="answer">0.85</option>
<option value="">0.15</option></select></p>
</div>
</div>
<p>Besides our usual model checks and model evaluation metrics, when dealing with proportional data sometimes we find that the observed variability in the data is greater than the one expected by the model, i.e.&nbsp;<span class="math inline">\(Var(Y) = n ~p~ (1-p)\)</span>.</p>
<p>This excess of variance is called <strong>overdispersion</strong> and its an indicator that our model is missing some important variability in the data (e.g.&nbsp;unaccounted factors affecting the probability of an event, non-independent trials, clustering within the data, among others).</p>
<p>To check for overdispersion we can use the built-in <code><a href="https://easystats.github.io/performance/reference/check_overdispersion.html">check_overdispersion()</a></code> function from the <code>performance</code> package (to learn more about overdispersion see <span class="citation" data-cites="gelman2006">Gelman and Hill (<a href="#ref-gelman2006" role="doc-biblioref">2006</a>)</span>):</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_overdispersion.html">check_overdispersion</a></span><span class="op">(</span><span class="va">model_turtles</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Overdispersion test

 dispersion ratio = 1.250
          p-value = 0.176</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>No overdispersion detected.</code></pre>
</div>
</div>
<p>In this example its seems we don’t have to worry about it. But what about the binary case (i.e.&nbsp;ungrouped data)? well overdispersion is usually not a concern here because the variance cannot exceed the range for a binary response where each observation represents a single outcome (0 or 1) and the variance of the model is constrained since <span class="math inline">\(Var(Y) = p(1-p)\)</span>.</p>
<section id="modelling-grouped-binary-data-with-a-categorical-covariate" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="modelling-grouped-binary-data-with-a-categorical-covariate">
<span class="header-section-number">2.1</span> Modelling grouped binary data with a categorical covariate</h2>
<p>In the last section we reviewed the case when the explanatory variable was continuous., lets look now at the case when the explanatory variable is categorical.</p>
<p>To illustrate how the previous model works with categorical predictors we can discretized the temperature values into arbitrary categories as follows:</p>
<p><span class="math display">\[
\mathrm{temperature~ category} =\begin{cases} \mathrm{temperature} &gt; 29^\circ C  &amp;  \text{high} \\ \mathrm{temperature} &gt; 28^\circ C&amp; \text{medium} \\ \text{else} &amp; \text{low}\end{cases}
\]</span></p>
<p>In R we can use the <code>case_when()</code> function to accomplish this:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">turtles</span> <span class="op">=</span> <span class="va">turtles</span>  <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">mutate</span><span class="op">(</span></span>
<span>  temp_fct <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span></span>
<span>    <span class="va">temp</span> <span class="op">&gt;</span> <span class="fl">29</span> <span class="op">~</span> <span class="st">"high"</span>,</span>
<span>    <span class="va">temp</span> <span class="op">&gt;</span> <span class="fl">28</span> <span class="op">~</span> <span class="st">"medium"</span>,</span>
<span>    .default <span class="op">=</span> <span class="st">"low"</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, recall that as usual, R will set the baseline category for our explanatory variable in alphabetical order, i.e.&nbsp;the <code>high</code> temperature level will be treated as reference for the dicretized variable. However, we already know that the chances of a male being hatched increases with higher incubation temperatures.</p>
<p>Thus, it makes sense to assess how the chances of a male being hatched are affected by comparing higher temperature categories against lower ones. This implies that we will set <code>low</code> to be our reference category. Luckily, we have seen in previous tasks how to do this using the <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">turtles</span> <span class="op">=</span> <span class="va">turtles</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>temp_fct <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">temp_fct</span>,ref <span class="op">=</span> <span class="st">"low"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now fit a logistic regression using the <code>low</code> temperature level as the reference category for our dicretized temperature covariate. The model is then given by:</p>
<span class="math display">\[\begin{align}
y_i &amp;\sim \mathrm{Binomial}(n_ip_i)\\
\mathrm{logit}(p_i) &amp;= \alpha +  \beta_{1}  \times \mathbb{I}_{\mathrm{temperature}}(\mathrm{high}) + \beta_{2}  \times \mathbb{I}_{\mathrm{temperature}}(\mathrm{medium}).
\end{align}\]</span>
<ul>
<li><p><span class="math inline">\(\alpha\)</span> represent the <strong>log-odds</strong> of a male turtle being hatched in <code>low</code> incubation temperature.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> are the change int the <strong>log-odds</strong> of a male turtle being hatched given it was incubated in a <code>high</code> temperature condition compared to a <code>low</code> one.</p></li>
<li><p><span class="math inline">\(\mathbb{I}_{\mathrm{temperature}}(\mathrm{high})\)</span> is an indicator variable that takes the value of 1 if the <span class="math inline">\(i\)</span>th experiment replicate was conducted on a <code>high</code> temperature.</p></li>
<li><p><span class="math inline">\(\beta_2\)</span> are the change int the <strong>log-odds</strong> of a male turtle being hatched given it was incubated in a <code>medium</code> condition compared to a <code>low</code> one.</p></li>
<li><p><span class="math inline">\(\mathbb{I}_{\mathrm{temperature}}(\mathrm{medium})\)</span> is an indicator variable that takes the value of 1 if the <span class="math inline">\(i\)</span>th experiment replicate was conducted on a <code>medium</code> temperature.</p></li>
</ul>
<p>In R, the model can be fitted as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_turtles_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">male</span>,<span class="va">female</span><span class="op">)</span> <span class="op">~</span> <span class="va">temp_fct</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">turtles</span>,</span>
<span>                     family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets print the model estimates odds scale and 95% confidence intervals (remember we can achieve this by setting <code>conf.int=TRUE</code> and <code>exponentiate=TRUE</code> within the <code>tidy</code> function):</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_turtles_2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">T</span>,exponentiate <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">-1.80</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">1.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">temp_fcthigh</td>
<td style="text-align: right;">45.47</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">8.59</td>
<td style="text-align: right;">843.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">temp_fctmedium</td>
<td style="text-align: right;">6.32</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">4.23</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.76</td>
<td style="text-align: right;">15.31</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can see that the odds of a male being hacthed if it was incubated on a <code>low</code> temperature condition are 0.59 the odds of a female being hatched if it was incubated on the same condition.</p>
<p>Alternatively, we could interpret this as the odds of female being hatched in a <code>low</code> temperature incubation settings being <span class="math inline">\(\mathrm{exp}(\alpha)^{-1} =\)</span> 1.68 higher than the odds of a male being hatched under the same setting. However, there is not enough evidence to support that the change in the odds is statistically significant since the confidence interval ( 0.33 , 1.04) contains 1 (remember we are in the odds scale).</p>
<p>On the other hand, the odds of a male being hatched are 45.47! significantly higher in a <code>high</code> temperature setting compared to a <code>low</code> temperature. Likewise, the odds of a male being hatched are 6.32 higher in a <code>medium</code> temperature condition compared to a <code>low</code> one.</p>
<p>What if we want to compare the odds of a male being hatched if the egg was incubate on a <code>high</code> temperture conditon against a <code>medium</code> one?</p>
<p>In that case, we we will be looking at the following odds ratio:</p>
<span class="math display">\[\begin{align}
\dfrac{\mathrm{Odds}(\mathrm{male}=1|\mathrm{temperature}=high)}{\mathrm{Odds}(\mathrm{male}=1|\mathrm{temperature}=medium)} &amp;= \dfrac{\mathrm{exp}(\alpha+\beta_1)}{\mathrm{exp}(\alpha+\beta_2)} \\
&amp;= \mathrm{exp}(\alpha+\beta_1 - \alpha - \beta_2) \\
&amp;= \mathrm{exp}(\beta_1 - \beta_2) = \frac{\mathrm{exp}(\beta_1)}{ \mathrm{exp}(\beta_2)}
\end{align}\]</span>
<p>Where <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> are the coefficients in the <strong>log-odd</strong> scale. However since we already have <span class="math inline">\(\mathrm{exp}(\beta_1)=\)</span> 45.47 and <span class="math inline">\(\mathrm{exp}(\beta_2)=\)</span> 6.32, then the odds of male being hatched from an egg that was incubated on a <code>high</code> temperature condition are <span class="math inline">\(\frac{45.47}{6.32}=\)</span> 7.2 greater than the one that was incubate on a <code>medium</code> temperature condition.</p>
<p>Finally, we can calculate the probabilities of a male being hatched in each temperature condition as follows:</p>
<ul>
<li>
<p><span class="math inline">\(P(\mathrm{male}=1|\mathrm{temperature}=low) = \dfrac{\mathrm{\mathrm{exp}(\alpha})}{1 + \mathrm{exp}(\alpha)}.\)</span> In R this is:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model_turtles_2</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   0.372549 </code></pre>
</div>
</div>
</li>
<li>
<p><span class="math inline">\(P(\mathrm{male}=1|\mathrm{temperature}=medium) = \dfrac{\mathrm{\mathrm{exp}(\alpha + \beta_1})}{1 + \mathrm{exp}(\alpha + \beta_1)}.\)</span> In R this is equivalent to:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model_turtles_2</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model_turtles_2</span><span class="op">)</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.7894737 </code></pre>
</div>
</div>
</li>
<li>
<p><span class="math inline">\(P(\mathrm{male}=1|\mathrm{temperature}=high) = \dfrac{\mathrm{\mathrm{exp}(\alpha + \beta_2})}{1 + \mathrm{exp}(\alpha + \beta_2)}\)</span>. In R this is computed as:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model_turtles_2</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model_turtles_2</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.9642857 </code></pre>
</div>
</div>
</li>
</ul>
<p>We can visualize this probabilities using the <code><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model()</a></code> function as follows:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_model.html">plot_model</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">"pred"</span>,</span>
<span>           <span class="va">model_turtles_2</span>,</span>
<span>           terms <span class="op">=</span> <span class="st">"temp_fct"</span>,</span>
<span>           axis.title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Temperature Category"</span>,</span>
<span>                          <span class="st">"Prob. of a hatchling being male"</span><span class="op">)</span>,</span>
<span>           title <span class="op">=</span> <span class="st">" "</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="models-for-multiple-categorical-responses" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Models for multiple categorical responses</h1>
<p>Now that we have covered GLMs for categorical responses with two possible outcomes, we will generalise this to situations where the response variable is categorical with more than two categories. More specifically, we will look at logistic regression models applied to <strong>nominal</strong> (unordered) responses with <strong>more than two categories</strong>.</p>
<p>The basis for modelling categorical data with more than two categories is the <strong>multinomial distribution</strong>.</p>
<p>Consider a random variable <span class="math inline">\(Y\)</span> with <span class="math inline">\(J\)</span> categories. Let <span class="math inline">\(p_1,p_2,\dots, p_J\)</span> be the respective probabilities associated with each of the <span class="math inline">\(J\)</span> categories, with <span class="math inline">\(\sum_j^J p_j = 1\)</span>. Suppose there are <span class="math inline">\(n\)</span> independent observations which result in <span class="math inline">\(y_1\)</span> outcomes in category 1, <span class="math inline">\(y_2\)</span> outcomes in category 2, and so on. Let <span class="math inline">\(\mathbf{y}=(y_1,y_2,\dots,y_J)^\intercal\)</span> with <span class="math inline">\(\sum_{j=1}^J y_j = n\)</span>. We say that <span class="math inline">\(\mathbf{y}\)</span> follows a <strong>multinomial distribution</strong> with probability mass function (p.m.f.)</p>
<p><span id="eq-multinomial"><span class="math display">\[
f(\mathbf{y} | n)=\frac{n!}{y_1! y_2! \dots y_J!}p_1^{y_1}p_2^{y_2}\dots p_J^{y_J}.
\tag{1}\]</span></span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">\(J=2\)</span> then <span class="math inline">\(p_2=1-p_1\)</span> and <span class="math inline">\(y_2=n-y_1\)</span> so the expression above reduces to the p.m.f. of the binomial distribution:</p>
<p><span class="math display">\[
f(\mathbf{y} | n)=\frac{n!}{y_1! (n-y_1)!} p_1^{y_1}p_2^{n-y_1}
\]</span></p>
</div>
</div>
<p>For the multinomial distribution, we have the following expressions for the mean, variance and covariance:</p>
<span class="math display">\[\begin{align*}
\textrm{E}(Y_j)&amp;=np_j\\
\textrm{Var}(Y_j)&amp;=np_j(1-p_j)\\
\textrm{Cov}(Y_j,Y_k)&amp;= -n p_jp_k
\end{align*}\]</span>
<p>Notice also the negative covariance between <span class="math inline">\(Y_j\)</span> and <span class="math inline">\(Y_k\)</span> due to the sum constraint <span class="math inline">\(\sum_{j=1}^J y_j = n\)</span>.</p>
<p>In general, the multinomial model does not satisfy the exponential family distribution requirement for the response in a GLM, but we can still fit GLMs to multinomial responses thanks to its relationship with the Poisson distribution, which is a member of the exponential family.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-pencil-square " style="color: #c8793c;" role="img" aria-hidden="true"></i> Task
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(Y_j \sim \text{Po}(\mu_j)\)</span> where the <span class="math inline">\(Y_j\)</span> are independent for <span class="math inline">\(j=1,\dots,J\)</span> with <span class="math inline">\(\mu_j\)</span> the expected number of events. Their joint p.m.f. is: <span class="math display">\[ f(\mathbf{y})=\prod_{j=1}^J \frac{\mu_j^{y_j}e^{-\mu_j}}{y_j!}.\]</span></p>
<p>The random variable <span class="math inline">\(N=Y_1+Y_2+\dots+Y_J\)</span> follows a <span class="math inline">\(\mathrm{Poisson}(\mu_1+\mu_2+\dots+\mu_J)\)</span> density , i.e.&nbsp;<span class="math display">\[f(n) = \dfrac{\left(\sum_{j=1}^J\mu_j\right)^ne^{-\sum_{j=1}^J\mu_j}}{n!}.\]</span></p>
Conditional on <span class="math inline">\(N\)</span>, show that <span class="math inline">\(\mathbf{y}\)</span> follows a multinomial distribution.
<div class="webex-solution">
<button>
Take hint
</button>
<p>When we condition on the observed total number of events <span class="math inline">\(N=n\)</span>, the conditional probability <span class="math inline">\(f(\mathbf{y}|n) = \dfrac{f(\mathbf{y},n)}{f(n)} = \dfrac{f(y_1,y_2,\ldots,y_n)}{f(n)}\)</span> since <span class="math inline">\(N = \sum_{j=1}^J Y_j\)</span>. Thus, conditional on <span class="math inline">\(N=n\)</span>, <span class="math inline">\(\mathbf{y}\)</span> has the following distribution:</p>
<p><span class="math display">\[
f(\mathbf{y} |n ) =\frac{\prod_{j=1}^J \mu_j^{y_j}e^{-\mu_j}/y_j!}{(\mu_1+\mu_2+\dots+\mu_J)^ne^{-(\mu_1+\mu_2+\dots+\mu_J)}/n!}
\]</span></p>
</div>
<div class="webex-solution">
<button>
See solution
</button>
<p>Conditional on <span class="math inline">\(N=n\)</span>, <span class="math inline">\(\mathbf{y}\)</span> has the following distribution:</p>
<p><span class="math display">\[
f(\mathbf{y} |n ) =\frac{\prod_{j=1}^J \mu_j^{y_j}e^{-\mu_j}/y_j!}{(\mu_1+\mu_2+\dots+\mu_J)^ne^{-(\mu_1+\mu_2+\dots+\mu_J)}/n!}
\]</span></p>
<p>which can be simplified as:</p>
<span class="math display">\[\begin{align}
f(\mathbf{y} |n ) &amp;=\dfrac{\left(\prod_{j=1}^J \frac{\mu_j^{y_j}}{y_j!}\right)\color{red}{e^{-\sum_{j=1}^J \mu_j}}}{ \frac{(\mu_1+\mu_2+\dots+\mu_J)^n\color{red}{e^{-\sum_{j=1}^J \mu_j}}}{n!}} \\
&amp;= \dfrac{n!}{y_1!y_2!\ldots y_J!}\dfrac{\prod_{j=1}^J\mu_j^{y_j}}{(\mu_1+\mu_2+\dots+\mu_J)^n}
\end{align}\]</span>
<p>Letting <span class="math inline">\(n= \sum_{j=1}^J y_j\)</span> and <span class="math inline">\(p_j = \dfrac{\mu_j}{\mu_1+\ldots+\mu_J}\)</span>, s.t. <span class="math inline">\(\sum_{j=1}^J p_j=1\)</span></p>
<span class="math display">\[\begin{align}
f(\mathbf{y}|n)&amp;= \dfrac{n!}{y_1!y_2!\ldots y_J!} \prod_{j=1}^J
\left(\dfrac{\mu_j}{\mu_1+\ldots+\mu_J}\right)^{y_j} \\
&amp;= \dfrac{n!}{y_1!y_2!\ldots y_J!} \prod_{j=1}^Jp _j^{y_j}
\end{align}\]</span>
<p>which is the same as the expression for the multinomial p.m.f. in <a href="#eq-multinomial" class="quarto-xref">Equation&nbsp;1</a></p>
</div>
</div>
</div>
<section id="nominal-logistic-regression" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="nominal-logistic-regression">
<span class="header-section-number">3.1</span> Nominal logistic regression</h2>
<p>Nominal logistic regression, also known as <em>multinomial logistic regression</em> is used when there is no natural order among the response categories, for example:</p>
<ul>
<li>Eye colour: Blue, Green, Brown, Hazel</li>
<li>House types: Bungalow, Duplex, Terrace</li>
<li>Type of pet: Dog, Cat, Rodent, Fish, Bird</li>
<li>Genotype: AA, Aa, aa</li>
</ul>
<p>The goal is to estimate the probabilities for each class <span class="math inline">\(j\)</span> (where <span class="math inline">\(j \in \{1,2,\ldots,J\}\)</span>) based on the independent variables <span class="math inline">\(\mathbf{x}\)</span>. The probability of the <span class="math inline">\(j\)</span>th class is then given by:</p>
<p><span class="math display">\[
P(Y=j|\mathbf{x})= \dfrac{\mathrm{exp}(\mathbf{x}^\intercal \boldsymbol{\beta}_j)}{\sum_{k=1}^J\mathrm{exp}(\mathbf{x}^\intercal \boldsymbol{\beta}_k)}
\]</span></p>
<p>Typically, one category is arbitrarily chosen as the reference category, and all other categories are compared with it. Suppose category <span class="math inline">\(J\)</span> is chosen as the reference category. The <strong>log-odds</strong> for the other categories relative to the reference are:</p>
<p><span id="eq-nominalresp"><span class="math display">\[
\mathrm{log}\left(\dfrac{P(Y=j|\mathbf{x})}{P(Y=J|\mathbf{x})}\right) = \mathrm{log}\left(\dfrac{p_j}{p_J}\right) =\mathbf{x}^\intercal\boldsymbol{\beta}_j, ~~\text{for } j=1,\dots,J-1.
\tag{2}\]</span></span></p>
</section><section id="parameter-estimation-and-fitted-values" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="parameter-estimation-and-fitted-values">
<span class="header-section-number">3.2</span> Parameter estimation and fitted values</h2>
<p>The <span class="math inline">\(J-1\)</span> log-odds in <a href="#eq-nominalresp" class="quarto-xref">Equation&nbsp;2</a> are solved simultaneously to estimate the parameters <span class="math inline">\(\boldsymbol{\beta}_j\)</span>.</p>
<p>Given parameter estimates <span class="math inline">\(\hat{\boldsymbol{\beta}}_j\)</span>, the linear predictors <span class="math inline">\(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j\)</span> can be calculated.</p>
<p>From <a href="#eq-nominalresp" class="quarto-xref">Equation&nbsp;2</a>, we derive:</p>
<p><span id="eq-pj"><span class="math display">\[
\hat{p}_j=\hat{p}_J\mathrm{exp}(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j)
\tag{3}\]</span></span></p>
<p>Now we can express <span class="math inline">\(\hat{p}_J\)</span> in terms of the other probabilities by using the fact that <span class="math inline">\(\sum_{j=1}^{J-1} \hat{p}_j + \hat{p}_J = \hat{p}_1+\hat{p}_2+\dots+\hat{p}_J= 1.\)</span> For instance, substituting <a href="#eq-pj" class="quarto-xref">Equation&nbsp;3</a> for <span class="math inline">\(j = 1,\ldots,J-1\)</span> in the sumation above yields to:</p>
<p><span class="math display">\[
\sum_{j=1}^{J-1} \hat{p}_J\mathrm{exp}(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j) + \hat{p}_J = 1.
\]</span></p>
<p>Solving for <span class="math inline">\(\hat{p}_J\)</span> yields to</p>
<p><span id="eq-p1hat"><span class="math display">\[
\hat{p}_J\left(\sum_{j=1}^{J-1} \mathrm{exp}(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j) + 1\right) = 1 \\ \Rightarrow\hat{p}_J = \dfrac{1}{1+\sum_{j=1}^{J-1} \mathrm{exp}(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j)}
\tag{4}\]</span></span></p>
<p>Hence, the probabilities for each class are:</p>
<ul>
<li><p>For the reference class <span class="math inline">\(J:\)</span><span class="math display">\[
    \hat{p}_J = \dfrac{1}{1+\sum_{j=1}^{J-1} \mathrm{exp}(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j)}
    \]</span></p></li>
<li><p>By substituting <span class="math inline">\(\hat{p}_J\)</span> in <a href="#eq-pj" class="quarto-xref">Equation&nbsp;3</a> we find <span class="math inline">\(\hat{p}_j\)</span> for class <span class="math inline">\(j = 1,2,\ldots,J-1:\)</span> <span id="eq-pjhat"><span class="math display">\[\hat{p}_j=\dfrac{\exp(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j)}{1+\sum_{j=1}^{J-1}\exp(\mathbf{x}^\intercal\hat{\boldsymbol{\beta}}_j)}. \tag{5}\]</span></span></p></li>
</ul>
<p>Fitted values (expected frequencies) can be calculated for each covariate pattern by multiplying the estimated probabilities <span class="math inline">\(\hat{p}_j\)</span> by the total frequency of the covariate pattern. Parameter estimates <span class="math inline">\(\hat{\boldsymbol{\beta}}_j\)</span> depend on the choice of reference category, but estimated probabilities and hence, fitted values (predicted counts), don’t.</p>
</section><section id="example-fitting-a-nominal-logistic-regression-in-r" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="example-fitting-a-nominal-logistic-regression-in-r">
<span class="header-section-number">3.3</span> Example: Fitting a nominal logistic regression in R</h2>
<p>In this example we look at data on subjects that were interviewed about the importance of various features when buying a car<span class="citation" data-cites="mcfadden2000">(<a href="#ref-mcfadden2000" role="doc-biblioref">McFadden et al. 2000</a>)</span>.</p>
<p>We focus in particular on the importance of power steering and air conditioning. The variables available in this dataset are:</p>
<ul>
<li>
<code>sex</code>: woman/man</li>
<li>
<code>age</code>: 18-23, 24-40, &gt;40</li>
<li>
<code>response</code>: no/little, important, very important</li>
<li>
<code>frequency</code>: number of interviewed people on each group</li>
</ul>
<p>The data set is available on the <code>dobson</code> R package. Lets begin loading it and produce some exploratory plots.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dcars</span> <span class="op">=</span> <span class="fu">dobson</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/dobson/man/Cars.html">Cars</a></span></span>
<span></span>
<span><span class="va">dcars</span><span class="op">$</span><span class="va">response</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">dcars</span><span class="op">$</span><span class="va">response</span>, </span>
<span>                         levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"no/little"</span>, <span class="st">"important"</span>, <span class="st">"very important"</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">dcars</span><span class="op">$</span><span class="va">age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">dcars</span><span class="op">$</span><span class="va">age</span>, </span>
<span>                         levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"18-23"</span>, <span class="st">"24-40"</span>, <span class="st">"&gt; 40"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">sex</th>
<th style="text-align: left;">age</th>
<th style="text-align: left;">response</th>
<th style="text-align: right;">frequency</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">women</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">women</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">women</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">women</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">women</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">women</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">women</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">women</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">women</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">41</td>
</tr>
<tr class="even">
<td style="text-align: left;">men</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">men</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">men</td>
<td style="text-align: left;">18-23</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">men</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">men</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">men</td>
<td style="text-align: left;">24-40</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">men</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">no/little</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">men</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">important</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">men</td>
<td style="text-align: left;">&gt; 40</td>
<td style="text-align: left;">very important</td>
<td style="text-align: right;">18</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the plots of the data below, we can see that quite a large proportion of people – a little over 58% in the over 40 category considered the features <em>very important</em> and, similarly 60% of young people (18-23 years old) considered these features as having <em>no or little importance</em>. Sex also seems to have an impact on car feature preferences, with over 40% of men considering the features of <em>no or little importance</em> and over 40% of women considering them <em>very important</em>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">R Plot</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">R Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Preferences for air conditioning and power steering in cars by gender and age.</figcaption></figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dcars</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>,</span>
<span>                   y <span class="op">=</span> <span class="va">frequency</span>, </span>
<span>                   fill <span class="op">=</span> <span class="va">response</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>      <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"identity"</span>,</span>
<span>               position <span class="op">=</span> <span class="st">"dodge"</span> <span class="op">)</span><span class="op">+</span></span>
<span>   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age groups"</span>,y <span class="op">=</span><span class="st">"Frequency"</span><span class="op">)</span><span class="op">+</span></span>
<span>   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Response category"</span>,</span>
<span>                     values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>,<span class="st">"purple"</span>,<span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span> </span>
<span> </span>
<span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dcars</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sex</span>,</span>
<span>                   y <span class="op">=</span> <span class="va">frequency</span>, </span>
<span>                   fill <span class="op">=</span> <span class="va">response</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>      <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"identity"</span>,</span>
<span>               position <span class="op">=</span> <span class="st">"dodge"</span> <span class="op">)</span><span class="op">+</span></span>
<span>   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sex"</span>,y <span class="op">=</span><span class="st">"Frequency"</span><span class="op">)</span><span class="op">+</span></span>
<span>      <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Response category"</span>,</span>
<span>                        values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"darkorange"</span>,<span class="st">"purple"</span>,<span class="st">"cyan4"</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Although the response is really an ordinal variable, we will treat it as nominal with “no/little importance” as the reference category (also occasionally referred to as “unimportant” in the rest for brevity.). Similarly we will initially regard <code>age</code> as nominal.</p>
<p>We can fit the following <strong>nominal logistic regression model</strong> using the <code><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom()</a></code> function from <code><a href="http://www.stats.ox.ac.uk/pub/MASS4/">library(nnet)</a></code>:</p>
<p><span class="math display">\[
\mathrm{log}\left(\frac{p_j}{p_1} \right) = \beta_{0j}+\beta_{1j}x_1+\beta_{2j}x_2+\beta_{3j}x_3, ~~ j=2,3
\]</span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(j=1\)</span> for “no/little importance” (the reference category)</li>
<li>
<span class="math inline">\(j=2\)</span> for “important”</li>
<li>
<span class="math inline">\(j=3\)</span> for “very important”</li>
<li>
<span class="math inline">\(x_1=1\)</span> for women and 0 for men,</li>
<li>
<span class="math inline">\(x_2=1\)</span> for age 24-40 years and 0 otherwise</li>
<li>
<span class="math inline">\(x_3=1\)</span> for age <span class="math inline">\(&gt;\)</span> 40 years and 0 otherwise.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">nnet</a></span><span class="op">)</span></span>
<span><span class="va">model_cars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span>, weight <span class="op">=</span> <span class="va">frequency</span>, data <span class="op">=</span> <span class="va">dcars</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  15 (8 variable)
initial  value 329.583687 
iter  10 value 290.566455
final  value 290.351098 
converged</code></pre>
</div>
</div>
<p>Notice that model converged after 10 iterations, the default number of iteration is set to 100 but you can modify this by setting <code>maxit=X</code> where <code>X</code> is the number of iterations after which the algorithm will stop.</p>
<p>Let look at model summaries and interpret the coefficients.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">model_cars</span>,conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">y.level</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">important</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.98</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">-3.82</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-1.48</td>
<td style="text-align: right;">-0.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">important</td>
<td style="text-align: left;">age24-40</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">1.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">important</td>
<td style="text-align: left;">age&gt; 40</td>
<td style="text-align: right;">1.59</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">2.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">important</td>
<td style="text-align: left;">sexwomen</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.85</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">-5.60</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-2.50</td>
<td style="text-align: right;">-1.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">age24-40</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">2.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">age&gt; 40</td>
<td style="text-align: right;">2.92</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">6.90</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">3.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">sexwomen</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">2.53</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">1.44</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice the two sets of coefficients, for the categories <code>important</code> and <code>very important</code> that correspond to the two log-odds equations comparing these to the baseline, which is <code>no/little importance</code>.</p>
<p>We can interpret these coefficients in terms of odds for each logit equation. For example:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">model_cars</span>,conf.int<span class="op">=</span><span class="cn">T</span>,exponentiate <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">y.level</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">important</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">-3.82</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">important</td>
<td style="text-align: left;">age24-40</td>
<td style="text-align: right;">3.09</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">6.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">important</td>
<td style="text-align: left;">age&gt; 40</td>
<td style="text-align: right;">4.89</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.22</td>
<td style="text-align: right;">10.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">important</td>
<td style="text-align: left;">sexwomen</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">2.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">-5.60</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">age24-40</td>
<td style="text-align: right;">4.38</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">9.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">age&gt; 40</td>
<td style="text-align: right;">18.48</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">6.90</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">8.07</td>
<td style="text-align: right;">42.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">very important</td>
<td style="text-align: left;">sexwomen</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">2.53</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">4.23</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From this table, we can see that the odds of considering the features important (versus <code>no/little importance</code>) for over 40 year-olds are <strong>4.89</strong> times the odds for 18-23 year olds (which is the baseline category for the <code>age</code> group). In general, a positive coefficient (or greater than 1 odds multiplier) tells us that older people are more likely to consider the features important than young people, which is consistent with what we observed in the exploratory plots. Similarly, we can see that women are more likely than men to consider the features important, specifically the chances a woman finds these features <code>important</code> are 47% greater than men and more than twice consider these features as <code>very important</code> compared to men. However, in the first case, the difference between women and men is not statistically significant since the 95% CI contains 1.</p>
<p>In the table below we have a summary of the coefficients, odds ratios and confidence intervals for the <strong>log-odds</strong> corresponding to <code>important</code> versus <code>no/little importance</code>.</p>
</section><section id="model-checking-and-model-comparisons" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="model-checking-and-model-comparisons">
<span class="header-section-number">3.4</span> Model checking and model comparisons</h2>
<p>Summary statistics can be used to assess the adequacy of a model and also to compare models. Some of the statistics we can consider are:</p>
<ul>
<li>the <strong>deviance</strong> <span class="math inline">\(D=2[l(\hat{\boldsymbol{\beta}}_{\max})-l(\hat{\boldsymbol{\beta}})]\)</span> (also referred to as <em>residual deviance</em>), where <span class="math inline">\(l(\hat{\boldsymbol{\beta}}_{\max})\)</span> is the maximised log-likelihood for the saturated (full) model and <span class="math inline">\(l(\hat{\boldsymbol{\beta}})\)</span> is the maximised log-likelihood for the model of interest;</li>
<li>the <strong>likelihood ratio statistic</strong>, which is equal to the difference between the null deviance (deviance of the model with no predictors included) and the residual deviance for the model of interest;</li>
<li>the <strong>Akaike information criterion</strong> <span class="math inline">\(AIC=-2l(\hat{\boldsymbol{\beta}};\mathbf{y})+2p\)</span>, which equals the maximised log-likelihood of the model of interest plus a penalty term equal to twice the number of parameters in the model. The reason for this is that we can keep adding predictors to the model to improve the log-likelihood, but the cost is increased model complexity. The penalty term attempts to strike a balance between model complexity and how well the model fits.</li>
</ul>
<p>If the model fits well, the deviance will be asymptotically <span class="math inline">\(\chi^2(N-p)\)</span>, where <span class="math inline">\(N\)</span> is <span class="math inline">\(J-1\)</span> times the number of distinct covariate patterns in the data, and <span class="math inline">\(p\)</span> is the number of parameters estimated.</p>
<p>The likelihood ratio statistic will be asymptotically <span class="math inline">\(\chi^2[p-(J-1)]\)</span> because the null (minimal) model will have one parameter for each logit defined in <a href="#eq-nominalresp" class="quarto-xref">Equation&nbsp;2</a>.</p>
<p>The AIC can be used for model selection: calculate the criterion for each model and choose the one with the smallest value of the AIC.</p>
<p>We can compare the nominal logistic regression model with additive terms for <code>age</code> and <code>sex</code> with the null model by taking the difference in deviances (likelihood ratio test).</p>
<p>The null model can be fit as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_null</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="fl">1</span>, data<span class="op">=</span><span class="va">dcars</span>, weights<span class="op">=</span><span class="va">frequency</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  6 (2 variable)
initial  value 329.583687 
final  value 329.272024 
converged</code></pre>
</div>
</div>
<p>To see some model comparisson metrics we can use the <code><a href="https://generics.r-lib.org/reference/glance.html">glance()</a></code> function from the <code>broom</code> package:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">model_null</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    edf deviance   AIC  nobs
  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1     2     659.  663.    18</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">model_cars</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    edf deviance   AIC  nobs
  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1     8     581.  597.    18</code></pre>
</div>
</div>
<p>The difference in deviance is <span class="math inline">\(658.54-580.70=77.84\)</span> which is significant when compared with a <span class="math inline">\(\chi^2(8-2)\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">qchisq</a></span><span class="op">(</span>df<span class="op">=</span><span class="fl">6</span>, p<span class="op">=</span><span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.59159</code></pre>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># pval</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="fl">77.844</span>,df<span class="op">=</span><span class="fl">6</span>,lower.tail <span class="op">=</span> <span class="cn">F</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.955365e-15</code></pre>
</div>
</div>
<p>Overall, the explanatory variables are descriptive of car preferences.</p>
<p>We can also compare this model with the saturated (full) model, which includes an interaction between <code>age</code> and <code>sex</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_full</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">age</span> <span class="op">*</span> <span class="va">sex</span>, weight <span class="op">=</span> <span class="va">frequency</span>, data <span class="op">=</span> <span class="va">dcars</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  21 (12 variable)
initial  value 329.583687 
iter  10 value 288.541004
final  value 288.381742 
converged</code></pre>
</div>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">model_full</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    edf deviance   AIC  nobs
  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1    12     577.  601.    18</code></pre>
</div>
</div>
<p>The difference in deviance between the additive and the saturated model is <span class="math inline">\(580.70-576.76=3.94\)</span>. This is not significant when compared with a <span class="math inline">\(\chi^2(12-8)\)</span>, so the additive model appears to fit the data well.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">qchisq</a></span><span class="op">(</span>df<span class="op">=</span><span class="fl">4</span>, p<span class="op">=</span><span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.487729</code></pre>
</div>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># pval</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="fl">3.94</span>,df<span class="op">=</span><span class="fl">6</span>,lower.tail <span class="op">=</span> <span class="cn">F</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6847959</code></pre>
</div>
</div>
<p>The same conclusion is supported when comparing the AIC for these models:</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/performance/">performance</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://easystats.github.io/performance/reference/compare_performance.html">compare_performance</a></span><span class="op">(</span><span class="va">model_full</span>,<span class="va">model_cars</span>,<span class="va">model_null</span>,metrics <span class="op">=</span> <span class="st">"AIC"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">AIC_wt</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">model_full</td>
<td style="text-align: left;">multinom</td>
<td style="text-align: right;">600.76</td>
<td style="text-align: right;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">model_cars</td>
<td style="text-align: left;">multinom</td>
<td style="text-align: right;">596.70</td>
<td style="text-align: right;">0.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">model_null</td>
<td style="text-align: left;">multinom</td>
<td style="text-align: right;">662.54</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>the additive model has a smaller AIC of 596.7 compared to the interaction model which has AIC of 600.7.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="bi-pencil-square " style="color: #c8793c;" role="img" aria-hidden="true"></i> Task
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>iris</code> data set gives the measurements in centimeters of the variables sepal length and width and petal length and width, respectively, for 50 flowers from each of three species of iris: setosa, versicolor, and virginica. Suppose that we have these measurements from an iris and we wish to classify it into one of the three species.</p>
<p>Fit a nominal logistic regression model to the data and predict the probability of each species from the fitted model using sepal length as the only predictor.</p>
<p>Note that you can use the predicted probabilities from a nominal logistic regression model to classify an observation to the category with the highest predicted probability.</p>
<div class="webex-solution">
<button>
Take hint
</button>
<p>We can get a list which assigns each observation to the category with the highest predicted probability using <code>predict(your_model)</code>.</p>
</div>
<div class="webex-solution">
<button>
See solution
</button>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m.iris</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">Species</span> <span class="op">~</span> <span class="va">Sepal.Length</span>, data<span class="op">=</span><span class="va">iris</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 164.791843 
iter  10 value 91.337114
iter  20 value 91.035008
final  value 91.033971 
converged</code></pre>
</div>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">iris</span>,<span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m.iris</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species predict(m.iris)
1          5.1         3.5          1.4         0.2  setosa          setosa
2          4.9         3.0          1.4         0.2  setosa          setosa
3          4.7         3.2          1.3         0.2  setosa          setosa
4          4.6         3.1          1.5         0.2  setosa          setosa
5          5.0         3.6          1.4         0.2  setosa          setosa
6          5.4         3.9          1.7         0.4  setosa          setosa</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>In the car preferences example there was a natural ordering among the response categories that we have not accounted for. This ordering can be taken into account in the model specification. Unfortunately, we don’t have time to cover all of this in a single session. But please have a look at the extra material where we introduce the basis of <strong>ordinal logistic regression</strong> for ordered categorical responses.</p>



</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-gelman2006" class="csl-entry" role="listitem">
Gelman, Andrew, and Jennifer Hill. 2006. <span>“Data Analysis Using Regression and Multilevel/Hierarchical Models,”</span> December. <a href="https://doi.org/10.1017/cbo9780511790942">https://doi.org/10.1017/cbo9780511790942</a>.
</div>
<div id="ref-mcfadden2000" class="csl-entry" role="listitem">
McFadden, Michael, Jennifer Powers, Wendy Brown, and Michelle Walker. 2000. <span>“Vehicle and Driver Attributes Affecting Distance from the Steering Wheel in Motor Vehicles.”</span> <em>Human Factors: The Journal of the Human Factors and Ergonomics Society</em> 42 (4): 676–82. <a href="https://doi.org/10.1518/001872000779697971">https://doi.org/10.1518/001872000779697971</a>.
</div>
</div></section></div></main><!-- /main --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>