{
  "hash": "8685d310d7b3b9c32d7e944bc687256d",
  "result": {
    "markdown": "---\ntitle: |\n  | Data Analysis\n  | Week 4 Further Task Solutions\noutput:\n  pdf_document:\n    fig_caption: yes\n    latex_engine: xelatex\n    number_sections: no\n  html_document:\n    df_print: paged\nheader-includes: \\usepackage{float}\nalways_allow_html: true\n---\n\n\n\n\n\n\n\n# Tasks\n\n**Question**: Do the model assumptions hold?\n\n1.  Assess the model assumptions for the parallel regression lines model. Do they appear valid?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nevals_multiple <- evals %>%\n                  select(score, gender, age)\npar.model <- lm(score ~ age + gender, data = evals_multiple)\n```\n:::\n\n\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregression.points <- get_regression_points(par.model) \n\nggplot(regression.points, aes(x = age, y = residual)) + \n  geom_point() +\n   labs(x = \"age\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ gender)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\nggplot(regression.points, aes(x = score_hat, y = residual)) +\n geom_point() +\n   labs(x = \"Fitted values\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ gender)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-2-2.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\nggplot(regression.points, aes(x = residual)) +\n   geom_histogram(binwidth = 0.25, color = \"white\") +\n   labs(x = \"Residual\") +\n   facet_wrap(~gender)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-2-3.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n2.  Return to the `Credit` data set and fit a multiple regression model with `Balance` as the outcome variable, and `Income` and `Age` as the explanatory variables, respectively. Assess the assumptions of the multiple regression model.\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCred <- Credit |>\n  select(Balance, Income, Age)\n \nCred |>\n   skim()\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |Cred |\n|Number of rows           |400  |\n|Number of columns        |3    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|numeric                  |3    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|     sd|    p0|   p25|    p50|    p75|    p100|hist  |\n|:-------------|---------:|-------------:|------:|------:|-----:|-----:|------:|------:|-------:|:-----|\n|Balance       |         0|             1| 520.02| 459.76|  0.00| 68.75| 459.50| 863.00| 1999.00|▇▅▃▂▁ |\n|Income        |         0|             1|  45.22|  35.24| 10.35| 21.01|  33.12|  57.47|  186.63|▇▂▁▁▁ |\n|Age           |         0|             1|  55.67|  17.25| 23.00| 41.75|  56.00|  70.00|   98.00|▆▇▇▇▁ |\n:::\n\n```{.r .cell-code}\nCred |>\n   cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Balance    Income         Age\nBalance 1.000000000 0.4636565 0.001835119\nIncome  0.463656457 1.0000000 0.175338403\nAge     0.001835119 0.1753384 1.000000000\n```\n:::\n\n```{.r .cell-code}\nggplot(Cred, aes(x = Age, y = Balance)) +\n   geom_point() +\n   labs(x = \"Age (in years)\", y = \"Credit card balance (in $)\", \n        title = \"Relationship between balance and age\") +\n   geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n# plot_ly(Cred, x = ~Income, y = ~Age, z = ~Balance,\n#          type = \"scatter3d\", mode = \"markers\")\n \nBalance.model <- lm(Balance ~ Age + Income, data = Cred)\nget_regression_table(Balance.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept   360.      70.4        5.11   0       221.    498.   \n2 Age          -2.18     1.20      -1.82   0.069    -4.54    0.172\n3 Income        6.24     0.587     10.6    0         5.08    7.39 \n```\n:::\n\n```{.r .cell-code}\nregression.points <- get_regression_points(Balance.model)\n \nggplot(regression.points, aes(x = Income, y = residual)) +\n   geom_point() +\n   labs(x = \"Income (in $1000)\", y = \"Residual\", title = \"Residuals vs income\")  +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-3-2.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\nggplot(regression.points, aes(x = Age, y = residual)) +\n   geom_point() +\n   labs(x = \"Age (in years)\", y = \"Residual\", title = \"Residuals vs age\")  +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-3-3.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\nggplot(regression.points, aes(x = residual)) +\n   geom_histogram(color = \"white\") +\n   labs(x = \"Residual\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-3-4.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n3.  Return to the `Credit` data set and fit a parallel regression lines model with `Balance` as the outcome variable, and `Income` and `Student` as the explanatory variables, respectively. Assess the assumptions of the fitted model.\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n Cred <- Credit |>\n   select(Balance, Income, Student)\n \n Cred |>\n   skim()\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |Cred |\n|Number of rows           |400  |\n|Number of columns        |3    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|factor                   |1    |\n|numeric                  |2    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts       |\n|:-------------|---------:|-------------:|:-------|--------:|:----------------|\n|Student       |         0|             1|FALSE   |        2|No: 360, Yes: 40 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|     sd|    p0|   p25|    p50|    p75|    p100|hist  |\n|:-------------|---------:|-------------:|------:|------:|-----:|-----:|------:|------:|-------:|:-----|\n|Balance       |         0|             1| 520.02| 459.76|  0.00| 68.75| 459.50| 863.00| 1999.00|▇▅▃▂▁ |\n|Income        |         0|             1|  45.22|  35.24| 10.35| 21.01|  33.12|  57.47|  186.63|▇▂▁▁▁ |\n:::\n\n```{.r .cell-code}\n ggplot(Cred, aes(x = Income, y = Balance, color = Student)) +\n   geom_jitter() +\n   labs(x = \"Income (in $1000)\", y = \"Credit card balance (in $)\", color = \"Student\") +\n   geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n par.model <- lm(Balance ~ Income + Student, data = Cred)\n get_regression_table(par.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 7\n  term         estimate std_error statistic p_value lower_ci upper_ci\n  <chr>           <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept      211.      32.5        6.50       0   147.     275.  \n2 Income           5.98     0.557     10.8        0     4.89     7.08\n3 Student: Yes   383.      65.3        5.86       0   254.     511.  \n```\n:::\n\n```{.r .cell-code}\n regression.points <- get_regression_points(par.model)\n \n ggplot(regression.points, aes(x = Income, y = residual)) +\n   geom_point() +\n   labs(x = \"Income (in $1000)\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ Student)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-4-2.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n ggplot(regression.points, aes(x = Balance_hat, y = residual)) +\n   geom_point() +\n   labs(x = \"Fitted values\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ Student)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-4-3.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n ggplot(regression.points, aes(x = residual)) +\n   geom_histogram(color = \"white\") +\n   labs(x = \"Residual\") +\n   facet_wrap(~Student)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-4-4.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n**Trickier**\n\n4.  Load the library `datasets` and look at the `iris` data set of Edgar Anderson containing measurements (in centimeters) on 150 different flowers across three different species of iris. Fit an interaction model with `Sepal.Width` as the outcome variable, and `Sepal.Length` and `Species` as the explanatory variables. Assess the assumptions of the fitted model.\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n Irs <- iris |>\n   select(Sepal.Width, Sepal.Length, Species)\n \n Irs |>\n   skim()\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |Irs  |\n|Number of rows           |150  |\n|Number of columns        |3    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|factor                   |1    |\n|numeric                  |2    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                |\n|:-------------|---------:|-------------:|:-------|--------:|:-------------------------|\n|Species       |         0|             1|FALSE   |        3|set: 50, ver: 50, vir: 50 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate| mean|   sd|  p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|----:|----:|---:|---:|---:|---:|----:|:-----|\n|Sepal.Width   |         0|             1| 3.06| 0.44| 2.0| 2.8| 3.0| 3.3|  4.4|▁▆▇▂▁ |\n|Sepal.Length  |         0|             1| 5.84| 0.83| 4.3| 5.1| 5.8| 6.4|  7.9|▆▇▇▅▂ |\n:::\n\n```{.r .cell-code}\n Irs |> \n   get_correlation(formula = Sepal.Width ~ Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         cor\n1 -0.1175698\n```\n:::\n\n```{.r .cell-code}\n ggplot(Irs, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +\n   geom_point() +\n   labs(x = \"Sepal length (in centimetres)\", y = \"Sepal width (in centimetres)\", color = \"Species\") +\n   geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n int.model <- lm(Sepal.Width ~ Sepal.Length * Species, data = Irs)\n get_regression_table(int.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  term                    estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                      <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept                 -0.569     0.554     -1.03   0.306   -1.66     0.525\n2 Sepal.Length               0.799     0.11       7.24   0        0.58     1.02 \n3 Species: versicolor        1.44      0.713      2.02   0.045    0.032    2.85 \n4 Species: virginica         2.02      0.686      2.94   0.004    0.66     3.37 \n5 Sepal.Length:Speciesve…   -0.479     0.134     -3.58   0       -0.743   -0.215\n6 Sepal.Length:Speciesvi…   -0.567     0.126     -4.49   0       -0.816   -0.317\n```\n:::\n\n```{.r .cell-code}\n regression.points <- get_regression_points(int.model)\n \n ggplot(regression.points, aes(x = Sepal.Length, y = residual)) +\n   geom_point() +\n   labs(x = \"Sepal length (in centimetres)\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ Species)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-5-2.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n ggplot(regression.points, aes(x = Sepal.Width_hat, y = residual)) +\n   geom_point() +\n   labs(x = \"Fitted values\", y = \"Residual\") +\n   geom_hline(yintercept = 0, col = \"blue\", linewidth = 1) +\n   facet_wrap(~ Species)\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-5-3.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\n ggplot(regression.points, aes(x = residual)) +\n   geom_histogram(color = \"white\") +\n   labs(x = \"Residual\") +\n   facet_wrap(~ Species)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-5-4.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n# Further Tasks\n\nYou are encouraged to complete the following tasks by using Quarto to produce a single document which summarises all your work, i.e. the original questions, your R code, your comments and reflections, etc.\n\n1.  Data was collected on the characteristics of homes in the American city of Los Angeles (LA) in 2010 and can be found in the file `LAhomes.csv` on the Moodle page. The data contain the following variables:\n\n-   `city` - the district of LA where the house was located\n\n-   `type` - either `SFR` (Single Family Residences) or `Condo/Twh` (Condominium/Town House)\n\n-   `bed` - the number of bedrooms\n\n-   `bath` - the number of bathrooms\n\n-   `garage` - the number of car spaces in the garage\n\n-   `sqft` - the floor area of the house (in square feet)\n\n-   `pool` - `Y` if the house has a pool\n\n-   `spa` - `TRUE` if the house has a spa\n\n-   `price` - the most recent sales price (\\$US)\n\n    We are interested in exploring the relationships between `price` and the other variables.\n\n    Read the data into an object called `LAhomes` and answer the following questions.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\na.  By looking at the univariate and bivariate distributions on the `price` and `sqft` variables below, what would be a sensible way to proceed if we wanted to model this data? What care must be taken if you were to proceed this way?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gridExtra) # Package to display plots side by side\n\nhist1 <- ggplot(LAhomes, aes(x = price)) +\n          geom_histogram()\n\nhist2 <- ggplot(LAhomes, aes(x = sqft)) +\n          geom_histogram()\n\nhist1log <- ggplot(LAhomes, aes(x = log(price))) +\n             geom_histogram()\n\nhist2log <- ggplot(LAhomes, aes(x = log(sqft))) +\n             geom_histogram()\n\nplot1 <- ggplot(LAhomes, aes(x = sqft, y = price)) +\n          geom_point()\n\nplot2 <- ggplot(LAhomes, aes(x = log(sqft), y = log(price))) +\n          geom_point()\n\ngrid.arrange(hist1, hist2, hist1log, hist2log, plot1, plot2,\n             ncol = 2, nrow = 3)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n**Solution** Given the highly skewed nature of both `price` and `sqft` (as seen in both their histograms and their scatterplot) the use of the log transformation significantly reduces the skewness in the data and makes the scatterplot look more linear. Hence we should model the transformed variables `log(price)` and `log(sqft)` instead of the original variables.\n\nIf these transformations are employed, special care must be taken when interpreting the meaning of estimated model parameters since the data are no longer on the original units and the linear models of the logged variables will have a multiplicative effect, rather than an additive effect, in the original units.\n\n------------------------------------------------------------------------\n\nb.  Fit the simple linear model with `log(price)` as the response and `log(sqft)` as the predictor. Display the fitted model on a scatterplot of the data and construct a bootstrap confidence interval (using the percentiles of the bootstrap distribution) for the slope parameter in the model and interpret its point and interval estimates.\n\n*Hint:* Although you can supply the `lm()` function with terms like `log(price)` when you use the `infer` package to generate bootstrap intervals you the transformed variable needs to already exist. Use the `mutate()` function in the `dplyr` package to create new transformed variables.\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nLAhomes <- mutate(LAhomes,log.price = log(price), log.sqft = log(sqft))\n\nslr.model1 <- lm(log(price) ~ log(sqft), data = LAhomes) \n\nggplot(LAhomes,aes(x = log(sqft), y = log(price))) +\n  geom_point() +\n  geom_smooth(method = lm, se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\ncoeff <- slr.model1 |>\n          coef() \n\npercentile_beta_ci <- LAhomes |> \n  specify(log.price ~ log.sqft) |>\n  generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"slope\") |>\n  get_ci(level = 0.95, type = \"percentile\")\n```\n:::\n\n\n\nThe above plot shows the fitted line `log(price)`=2.7 + 1.44 `log(sqft)`. The point estimate of the slope parameter estimates that for every unit increase in `log(sqft)` the average `log(price)` of houses will increase by 1.44 US dollars. Another way of saying this is that each additional 1% of square footage produces an estimate of the average price which is 1.44% higher (i.e. there is a multiplicative effect in the original units).\n\n*Note: you must be careful to avoid causative interpretations. Additional square footage does not necessarily **cause** the price of a specific house to go up.*\n\nFurthermore, based on the bootstrap confidence interval, we are 95% confident that the interval from 1.4 up to 1.48 contains the true rate of increase in the average of the logged prices as `log(sqft)` increase. Because this interval does not contain zero we conclude that the relationship between `log(price)` and `log(sqft)` is statistically significant.\n\n------------------------------------------------------------------------\n\nc.  Repeat the analysis in part b. but with the log of the number of bathrooms (`bath`) as the single explanatory variable.\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nLAhomes <- mutate(LAhomes, log.bath = log(bath))\n\nslr.model2 <- lm(log(price) ~ log(bath), data = LAhomes) \n\nggplot(LAhomes,aes(x=log(bath),y=log(price)))+\n  geom_point()+\n  geom_smooth(method=lm, se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\ncoeff2 <- slr.model2 |>\n            coef() \n\npercentile_beta_ci2 <- LAhomes |> \n  specify(log.price ~ log.bath) |>\n  generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"slope\") |>\n  get_ci(level = 0.95, type = \"percentile\")\n```\n:::\n\n\n\nThe above plot shows the fitted line `log(price)`=12.23 + 1.43 `log(bath)`. The point estimate of the slope parameter estimates that for every unit increase in the log of the number of bathrooms in a house the average log of the prices of houses will increase by 1.43 US dollars. Another way of saying this is that each doubling of bathroom produces an estimate of the average price which is 143% higher (i.e. there is a multiplicative effect in the original units).\n\nFurthermore, based on the bootstrap confidence interval, we are 95% confident that the interval from 1.36 up to 1.49 contains the true rate of increase in the average of the logged prices as the log of the number of bathrooms increases. Because this interval does not contain zero we conclude that the relationship between `log(price)` and `log(bath)` is statistically significant.\n\n------------------------------------------------------------------------\n\nd.  Fit the multiple linear regression model using the **log transform of all the variables** `price` (as the response) and both `sqft` and `bath` (as the explanatory variables). Calculate the point and interval estimates of the coefficients of the two predictors separately. Compare their point and interval estimates to those you calculated in parts b. and c. Can you account for the differences?\n\n*Hint:* Remember that we didn't use bootstrapping to construct the confidence intervals for parameters in multiple linear regression models, but rather used the theoretical results based on assumptions. You can access these estimates using the `get_regression_table()` function in the `moderndive` package.\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmlr.model <- lm(log(price) ~ log(sqft)+log(bath), data = LAhomes) \n\ncoeff3 <- mlr.model |>\n            coef() \n\nmlr.model.est <- get_regression_table(mlr.model)\nglimpse(mlr.model.est)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 3\nColumns: 7\n$ term      <chr> \"intercept\", \"log(sqft)\", \"log(bath)\"\n$ estimate  <dbl> 2.514, 1.471, -0.039\n$ std_error <dbl> 0.262, 0.040, 0.045\n$ statistic <dbl> 9.601, 37.221, -0.862\n$ p_value   <dbl> 0.000, 0.000, 0.389\n$ lower_ci  <dbl> 2.000, 1.394, -0.128\n$ upper_ci  <dbl> 3.028, 1.549, 0.050\n```\n:::\n\n```{.r .cell-code}\npercentile_beta1_ci <- c(mlr.model.est$lower_ci[2], mlr.model.est$upper_ci[2])\npercentile_beta2_ci <- c(mlr.model.est$lower_ci[3], mlr.model.est$upper_ci[3])\npercentile_beta1_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.394 1.549\n```\n:::\n\n```{.r .cell-code}\npercentile_beta2_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.128  0.050\n```\n:::\n:::\n\n\n\nThe fitted model is `log(price)`=2.51 + 1.47 `log(sqft)` - 0.04 `log(bath)`. The first thing we notice is that the parameter associated with (the log of) the number of bathrooms has changed from 1.43 to -0.04. That it, its gone from having a positive relationship with the (log of) house prices in the single explanatory variable model to having a negative relationship when the size of the house was also included in the model. One reason for the switch in sign of the parameter estimate could be that for a house with a given size in (log) square feet, more (log) bathrooms means that less of the (log) square footage is used for bedrooms and other desirable space, thus reflecting a lower average home price. This illustrates the importance of **taking all other variables in the model into account and holding them constant** when we interpret individual parameter estimates in a multiple linear regression model. (See the \"Formal Analysis\" section [here](https://shiny.maths-stats.gla.ac.uk/mbock/DA_Week6MLR_8515/#section-regression-modelling-with-two-continuous-explanatory-variables) from Week 6's lab).\n\nTurning to the confidence intervals, the model still predicts that the (log) square footage of the home significantly positively affects the average (log) price, since the 95% confidence interval for the `log(sqft)` parameter is from from 1.39 up to 1.55 which doesn't contain zero. However, now the number of bathrooms no longer significantly affects the price since the 95% confidence interval for the `log(bath)` parameter is from from -0.13 up to 0.05 which does contain zero. This suggests that we drop the `log(bath)` term from the model and return to the simple linear regression model we used in part b.\n\n------------------------------------------------------------------------\n\ne.  Using the objective measures for model comparisons, which of the models in parts b., c. and d. would you favour? Is this consistent with your conclusions in part d.?\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel.comp.values.slr.model1 <- glance(slr.model1)\nmodel.comp.values.slr.model2 <- glance(slr.model2)\nmodel.comp.values.mlr.model <- glance(mlr.model)\n\nModels <- c('SLR(log(sqft))','SLR(log(bath))','MLR') \nbind_rows(model.comp.values.slr.model1, model.comp.values.slr.model2, \n          model.comp.values.mlr.model, .id = \"Model\") |>\n  select(Model,adj.r.squared,AIC,BIC) |>\n  mutate(Model=Models) |>  \n  kable(\n     digits = 2,\n     caption = \"Model comparison values for different models\", \n  )\n```\n\n::: {.cell-output-display}\nTable: Model comparison values for different models\n\n|Model          | adj.r.squared|     AIC|     BIC|\n|:--------------|-------------:|-------:|-------:|\n|SLR(log(sqft)) |          0.77| 2292.16| 2308.28|\n|SLR(log(bath)) |          0.58| 3289.80| 3305.92|\n|MLR            |          0.77| 2293.41| 2314.91|\n:::\n:::\n\n\n\nThe table lists $R_{adj}^2$, $AIC$ and $BIC$ which can be used to compare the three models. Both the criteria of minimizing $AIC$ and $BIC$ and maximizing $R_{adj}^2$ leads us to prefer the the model\n\n`log(price)`=2.7 + 1.44 `log(sqft)`\n\nwhich we first saw in part b. This agrees with our conclusions in part d.\n\n------------------------------------------------------------------------\n\n2.  You have been asked to determine the pricing of a New York City (NYC) Italian restaurant's dinner menu such that it is competitively positioned with other high-end Italian restaurants by analyzing pricing data that have been collected in order to produce a regression model to predict the price of dinner.\n\nData from surveys of customers of 168 Italian restaurants in the target area are available. The data can be found in the file `restNYC.csv` on the Moodle page. Each row represents one customer survey from Italian restaurants in NYC and includes the key variables:\n\n-   `Price` - price (in \\$US) of dinner (including a tip and one drink)\n-   `Food` - customer rating of the food (from 1 to 30)\n-   `Decor` - customer rating of the decor (from 1 to 30)\n-   `Service` - customer rating of the service (from 1 to 30)\n-   `East` - dummy variable with the value 1 if the restaurant is east of Fifth Avenue, 0 otherwise\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\na.  Use the `ggpairs` function in the `GGally` package (see the following code) to generate an informative set of graphical and numerical summaries which illuminate the relationships between pairs of variables. Where do you see the strongest evidence of relationships between `price` and the potential explanatory variables? Is there evidence of multicollinearity in the data?\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(GGally)\nrestNYC$East <- as.factor(restNYC$East) # East needs to be a factor\nggpairs(restNYC[, 4:8], aes(colour = East, alpha = 0.4)) # Including the `East` factor\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\nggpairs(restNYC[, 4:7], aes(alpha = 0.4)) # Without the `East` factor\n```\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-13-2.png){fig-align='center' fig-pos='H' width=70%}\n:::\n:::\n\n\n\n-   `price` shows a moderate to strong correlation with 'Food`,`Service`and`Decor\\`.\n-   The correlation between `Service` and `Food` (0.795) is the strongest evidence of multicollinearity in the data, followed by the correlation between `Service` and `Decor` (0.645)\n\n------------------------------------------------------------------------\n\nb.  Fit the simple linear model with `Price` as the response and `Service` as the predictor and display the fitted model on a scatterplot of the data. Construct a bootstrap confidence interval (using the standard error from the bootstrap distribution) for the slope parameter in the model.\n\n    Now fit a multiple regressing model of `Price` on `Service`, `Food`, and `Decor`. What happens to the significance of `Service` when additional variables were added to the model?\n\n------------------------------------------------------------------------\n\n**Solution**\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nslr.Service <- lm(Price ~ Service, data=restNYC)\n\nggplot(restNYC,aes(x=Service,y=Price))+\n  geom_point()+\n  geom_smooth(method=lm, se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](DA_Week4_Further_Tasks_Solutions_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' fig-pos='H' width=70%}\n:::\n\n```{.r .cell-code}\ncoeff.Service <- slr.Service |>\n                  coef() \n\npercentile_beta_Service_ci <- restNYC |> \n  specify(Price ~ Service) |>\n  generate(reps = 1000, type = \"bootstrap\") |> \n  calculate(stat = \"slope\") |>\n  get_ci(level = 0.95, type = \"se\", point_estimate=coeff.Service[2])\n\nmlr.Service.Food.Decor <- lm(Price ~ Service + Food + Decor, data=restNYC)\n\nget_regression_table(mlr.Service.Food.Decor) |>  \n  kable(\n     digits = 2,\n     caption = \"Parameter estimates for MLR model of Price on Service, Food, and Decor\", \n  )\n```\n\n::: {.cell-output-display}\nTable: Parameter estimates for MLR model of Price on Service, Food, and Decor\n\n|term      | estimate| std_error| statistic| p_value| lower_ci| upper_ci|\n|:---------|--------:|---------:|---------:|-------:|--------:|--------:|\n|intercept |   -24.64|      4.75|     -5.18|    0.00|   -34.03|   -15.26|\n|Service   |     0.14|      0.40|      0.34|    0.73|    -0.65|     0.92|\n|Food      |     1.56|      0.37|      4.17|    0.00|     0.82|     2.29|\n|Decor     |     1.85|      0.22|      8.49|    0.00|     1.42|     2.28|\n:::\n:::\n\n\n\nWhen only `Service` is included in the model, it appears significant (confidence interval using the standard error from the bootstrap: 2.27 up to 3.37, which doesn't contain zero). However, once `Food` and `Decor` are added into the model, that is no longer the case as can be seen in the confidence interval table above, which does contain zero.\n\n------------------------------------------------------------------------\n\nc.  What is the correct interpretation of the coefficient on `Service` in the linear model which regresses `Price` on `Service`, `Food`, and `Decor`?\n\n------------------------------------------------------------------------\n\n**Solution**\n\nWhen `Food` and `Decor` are in the model, `Service` is not statistically significant, therefore we cannot know whether it has a significant effect on modeling `Price`.\n",
    "supporting": [
      "DA_Week4_Further_Tasks_Solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}